### ISSUE TITLE
Begin preparing CSS for e-gedsh TEI

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#1]
Hi W

Here is a single entry that could be the basis for a start: https://github.com/srophe/e-gedsh/blob/master/egedshsample.xml

Could you please work up a simple transform for now?

D

**Comment by wsalesky** [comment]
First pass:
http://wwwb.library.vanderbilt.edu/gedesh/entry.html?id=http://gedsh.bethmardutho.org/Aba-I

**Comment by davidamichelson** [comment]
Ooh, so far so good. 

One immediate change the license here needs to be Creative Commons Attribution Non-Commercial 4.0 Unported License. Please make that change.

Don't make any other changes until I get you the rest of the data.

**Comment by wsalesky** [comment]
Okay done.

**Comment by wsalesky** [comment]
Should I set up a webhook to automatically update the data on the server when you update the files here?

**Comment by davidamichelson** [comment]
Another edit: please change "Copyright Vanderbilt University, Princeton University, and the Contributor(s), 2014." to "Copyright Beth Mardutho: The Syriac Institute, 2011."
