### ISSUE TITLE
Crossreference Entries

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#10]
There are 622 full entries (div/@type="entry") and 60 cross reference entries (div/@type="crossreference").

Some cross reference entries vary in kind. Some point to a single entry and should have a URL that takes the reader there.

Some point to variant spellings that might help the reader but not to any specific article. These should perhaps return a search result?

```
         <div type="crossreference">
            <head>Thomas</head>
            <ab type="crossreference">see also <ref type="cr">Toma and Tumo</ref></ab>
         </div>
```

These may need some breaking up into separate refs for the search.

**Comment by dlschwartz** [comment]
@davidamichelson and @wsalesky there are actually two issues here. 

The following "crossreferences" deal with alternate spellings: 
George see Gewargis (E. Syr.) and Giwargis (W. Syr.) as well as Giwargi and Grigor TEI line 28101ff)
Jacob see also Yaʿqub (TEI line 36971ff)
John see Iwannis, Yoḥannan (E. Syr.), and Yuḥanon (W. Syr.) (TEI line 37852ff)
Joseph see Yawsep (TEI line 37858ff)
Paul see Pawla and Pawlos (TEI line 50036ff)
Sergius see Sargis (TEI line 56850ff)
Simeon see Shemʿon and Shemʿun (TEI line 58986ff)
Thomas see also Toma and Tumo (TEI line 64265ff) 

The following "crossreferences" simply provide a general finding aid:
Dayr, Dayro see under individual saint’s name (TEI line 20376ff)
Monastery see under individual saint’s name (TEI line 46275ff)

The easiest way to deal with this would be to simply strip out all the tei and leave only text. That would remove the bad hyperlinks. It would show in browse the correct spellings to use in browse and search. Also, searches would return the range of spelling options as well. This isn't super sophisticated but it gets the job done.

An alternatively to the easy fix would be to treat the two things above differently. The general finding instructions would be deal with as above but the spelling variants would be dealt with differently. @wsalesky could you weigh in on having the variant spellings hyperlinked where clicking on the link would return search results for those spellings. If this is easy with some slight tweaks to the TEI elements wrapping those variant spellings, I think we should do it. If it's complicated, I say we just skip it and address the final problem.

That final problem that applies to all of the above is that the app inserts a line for the URI in each of these cases even though there are not URIs available. I could change the div type to something like "info" and then @wsalesky could turn off the create-URI feature for those di types. Does this sound like a good idea?

**Comment by wsalesky** [comment]
@dlschwartz @davidamichelson 
I have updated this to remove empty URL labels and links that don't go anywhere for the spelling variations. 

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html?lang=&sort=T

We can have a feature that links these variations to a search, but would need to add something to the TEI to wrap the individual terms or names together. Also not all variations should link to searches. For example: 

```
            <div type="crossreference">
                <head>Dayr, Dayro</head>
                <ab type="crossreference">see <ref rend="bold">under individual saint’s name</ref>
                </ab>
            </div>
```
This one should probably just remain plain text. 

This one however should link to a search for each name: 

```
            <div type="crossreference">
                <head>Thomas</head>
                <ab type="crossreference">see also <ref rend="bold">Toma and Tumo</ref>
                </ab>
            </div>
```

This one should link to a search for each name variant (right?) so we would have to wrap each name (or search phrase) in some tei that indicates I should execute a search. What do you think?

**Comment by dlschwartz** [comment]
I agree that it is fine to remove empty URL labels and links. This is all we need to do for the Dayr, Dayro and Monastery cases. 

It would be great if the search link can work.  Would the following do the trick?
`<div type="crossreference">
                <head>Thomas</head>
                <ab type="crossreference">see also <ref type="search">Toma</ref> and <ref type="search">Tumo</ref>
                </ab>
            </div>`

**Comment by dlschwartz** [comment]
By the way, I've removed the ref rend="bold" from the two instances where the "cross reference" is merely a finding aid, i.e. from Dayr/Dayro and Monastery cases listed above.  This would mean that if the ref type="search" works as a solution we could replace all of the current ref rend="bold" encoding and these ref type="search" examples would be the only refs left without target attributes.

**Comment by davidamichelson** [comment]
We need to fix this in search results:
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?q=Jacob

Where it generates a blank URI:

Jacob see also Yaʿqub

Jacob see also Yaʿqub
URI:

**Comment by davidamichelson** [comment]
@wsalesky Can you look into this with @dlschwartz please?

**Comment by dlschwartz** [comment]
@wsalesky We should have discussed this today. There are two issues here.

1. We get this odd thing in the search results for "Jacob" that generates a blank URI. This is because the automatic transformation from xml to tei wrapped some things in refs that it should not have wrapped. Regarding Dave's comment above, the weird thing here is that the search results show "also Yaʿqub" hyperlinked even though only "Yaʿqub" is wrapped in a ref element in the tei. The "also" was probably included in the ref in an earlier version and maybe we have some legacy data showing up in search results here.

2. The other related issue is the seven "cross reference" entries that really just suggest spelling/transliteration variants for certain personal names. If it is easy and convenient, it would be nice to have these show up in browse with a hyperlink that when selected performs a person name search for that/those name variants. This is not necessary though (please let me know if this is just a huge hassle that we should avoid). I will likely need to change the tei. Right now each of these is wrapped in a ref element with attribute rend="bold". If I wrapped these in ref type="search" would you be able to use that. Please feel free to suggest alternate encoding for these.

**Comment by wsalesky** [comment]
@dlschwartz I can easily add a search link if you indicate the terms you want searched via the ref/@type attribute. 'search' or 'lookup' would be fine. Let me know when it is the data and I will add a hook on the search and browse pages. (make sure each term has its own rend, so if there are two names in the see also, each name needs to be wrapped in individual ref element)

**Comment by wsalesky** [comment]
Done.

**Comment by dlschwartz** [comment]
@wsalesky Unfortunately this doesn't seem to be working for me. The links turn up an error: 

HTTP ERROR 404
Problem accessing /exist/apps/e-gedsh/entry/index.html. Reason:

    Document /db/apps/e-gedsh/entry/index.html not found
Powered by Jetty:// 9.3.9.v20160517

Also, the display doesn't work out quite right. For example, I get: "John _see , (), and ()_ IwannisYoḥannanYuḥanon" on the browse page for the following tei. Granted this is probably the most complicated of these cross references but they all display similarly.
`<head>John</head>
                <ab type="crossreference">see <ref type="lookup">Iwannis</ref>, <ref type="lookup">Yoḥannan</ref> (<abbr>E. Syr.</abbr>), and
                        <ref type="lookup">Yuḥanon</ref> (<abbr>W. Syr.</abbr>)
                </ab>`

**Comment by wsalesky** [comment]
@dlschwartz what link did you click on to generate that error?

**Comment by wsalesky** [comment]
@dlschwartz that second example is more complicated then I realized. I will rework the code to account for this type of cross ref. Thanks.

**Comment by dlschwartz** [comment]
@wsalesky I get the same error message when clicking on any of the links.

**Comment by wsalesky** [comment]
@dlschwartz Okay thanks.

**Comment by wsalesky** [comment]
@dlschwartz 
This entry uses tei:hi, not ref, so it is not picked up by the code, I can add the tei:hi element, or you can change the code to use tei:ref instead. 

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html?lang=&sort=G
George see Gewargis (E. Syr.) and Giwargis (W. Syr.) as well as Giwargi and Grigor
```
            <div type="crossreference">
                <head>George</head>
                <ab type="crossreference">see <hi rend="bold">Gewargis</hi> (<abbr>E. Syr.</abbr>) and <hi rend="bold">Giwargis</hi> (W.
                    Syr.) as well as <hi rend="bold">Giwargi</hi> and <hi rend="bold">Grigor</hi>
                </ab>
            </div>
```

**Comment by wsalesky** [comment]
@dlschwartz I think this most recent change should get all the issues mentioned above. Let me know if I missed anything.

**Comment by dlschwartz** [comment]
@wsalesky I'll change the hi to ref. When I changed these I just searched for ref rend="bold" so I missed all of the hi elements. They should be refs.

**Comment by dlschwartz** [comment]
@wsalesky I've made that change to the George cross reference. I trust this will get us what we need throughout. I've tested all the other cross references and they look good on the browse page. All the links work as well. Thanks Winona! I'll go ahead and close this issue.
