### ISSUE TITLE
issue with spaces

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#101]
this may be the same problem as previous issue. Entry on Darmo, Toma. Near end of entry text: Patr.'s has space before apostrophe on website that is not in XML. Line 17150.

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Darmo-Toma

**Comment by wsalesky** [comment]
Resolved
