### ISSUE TITLE
web hook

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#103]
The changes I made yesterday don't seem to show online.

Example: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Dinno-Nimatullah

also, following entries. This can be seen in cross-ref. not showing, but there are also other edits that don't seem to go through.

**Comment by wsalesky** [comment]
The webhook claims there was an error in the xml:

> The XML parser reported a problem: fatal error at (21194,42) : Element type "ref" must be followed by either attribute specifications, "&gt;" or "/&gt;".</message>

However, when uploading it manually it seems to update just fine. Remember to check for well- formedness, and let me know if it happens again. Thanks!
-Winona
