### ISSUE TITLE
how to distinguish people with same name on item list on website

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#104]
There are some people of the same name, e.g., Eliya. In the print version (via info box) they are distinguished by the date. This is also the distinction in the URI, so that is fine.
But if - as it has been in the XML - the info box is taken to be part of the header, this will appear twice on the website. So Eliya will be followed in large letters by 'mid 6th cent.' and then the same words appear in smaller font afterwards (because it is the info box). This is clearly NOT how it should be.
But when I take the info-box wording out of the entry title, we have in the scroll bar that lists entry titles two items with exactly the same name (Eliya) which is obviously not ideal. (Let me know if this explanation is not clear.)
So we will want a way to put this information in the scroll bar - in those cases only - but not into the entry head.

**Comment by davidamichelson** [comment]
Thanks, yes I recall this was an issue when we tried to cite those GEDSH articles in the Syriac Biographical Dictionary. I think we will have to make a slight editorial change to the print version to make this workable in an electronic environment. Let's discuss when we meet next week.

**Comment by wsalesky** [comment]
@upossekel Is this still an issue? If so can you clarify how you would like to see the display change?

**Comment by dlschwartz** [comment]
This issues looks resolved to me. I'll close it.
