### ISSUE TITLE
subtitles in display

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#105]
Would it be possible to visually enhance the subtitles in the online version? For example in the long entry on Exegesis it would be really helpful to have these stand out by means of size or spacing before next paragraph. This will speed up the process of proof reading.

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Exegesis-Old-Testament&num=206

In XML this is the label element 'subsection'.

**Comment by wsalesky** [comment]
Done!
