### ISSUE TITLE
bold text

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#106]
How do we write the XML for bold text that is NOT a cross-reference. This comes up in cross references to variants of the name. This is not a cross-reference to a particular entry, but just to the different version of the name - usually this would be several entries.

Example: George, line 24340. Text of GEDSH page 173.

**Comment by wsalesky** [comment]
I would say use the hi element with a rend attribute:
`<hi rend="bold">Giwargi and Grigor</hi>`

@davidamichelson ?

**Comment by dlschwartz** [comment]
@wsalesky is correct, that is how we should encode this with one small change. Each name should be wrapped in the hi element and the "and" excluded. I'm not sure if the app is already rendering hi rend="bold" or not @wsalesky. If not, can you please add that. Thanks.

**Comment by wsalesky** [comment]
It should be in the app already. Let me know if it does not render.

**Comment by dlschwartz** [comment]
Great, thanks Winona! @upossekel, feel free to close this issue if you see that the bold is rendering properly. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz I wonder if @upossekel is running into an issue with the schema? As in she is not getting the option for bold on the rend attribute, while entering the data into the xml?

**Comment by upossekel** [comment]
Yes, exactly. It was not on the menu, so to say. Only options for rend are italics and superscript. So I suppose we would need to add it, yes?

 

Thanks.

**Comment by wsalesky** [comment]
@dlschwartz @upossekel I think @dlschwartz has resolved this? If so we can close this issue.

**Comment by dlschwartz** [comment]
Yes, the schema now allows hi rend="bold".
