### ISSUE TITLE
Help undoing commits

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#107]
@wsalesky @davidamichelson 
I made a tiny change to the ODD for e-egedsh and it seems to have messed up the rng file in a way I cannot figure out. I don't want Ute to download it because it will stop her work. I also don't have time to fix it right now (I need to head home). Since I don't know how to undo commits, I could use some help. Thanks. Here are the commits: 
https://github.com/srophe/e-gedsh/commit/4ce1062f8986dad6591170a45dbe345779b1269a
https://github.com/srophe/e-gedsh/commit/380039b321bd8590cf02a0278b86633bcf7ad145

**Comment by wsalesky** [comment]
@dlschwartz @davidamichelson I reverted them. Please let me know if there are any issue.

**Comment by dlschwartz** [comment]
Thanks @wsalesky, now I just need to figure out what went wrong.

**Comment by wsalesky** [comment]
The fun part! ;)
