### ISSUE TITLE
issue with spaces near 'abbr' element

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#109]
This seems to be a new bug, as it appears no in the HTML but not on the printout I made some time ago: In entry on Georgian Chr., section C.4, the expression (ed. with FT etc.) has an extra space before the 'ed.' E.g., line 24450.
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Georgian-Christianity-Syriac-contacts-with&num=223

**Comment by wsalesky** [comment]
Fixed! Sorry about that!
