### ISSUE TITLE
Adding URIS with safe URL Characters to egesdh-version-0-1.xml

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#11]
@wsalesky Could you please do the following data transformation?

In egesdh-version-0-1.xml we need to create an safe URL URI for each entry. 

This in general should follow this pattern: 

http://gedsh.bethmardutho.org/entry-headword-in-safe-characters

e.g.

http://gedsh.bethmardutho.org/Aba-I

or 

http://gedsh.bethmardutho.org/Bar-Ali-Isho

I don't know the formal rules for safe URL characters but it appears that it is best to strip all non-ascii characters, spaces, and all punctuation

See: http://stackoverflow.com/questions/695438/safe-characters-for-friendly-url
"To avoid these pitfalls, you're pretty much limited to escaping everything except alphanumerics, dash, underscore, and period."

So in my mind the best result would be to allow only [A-Za-z0-9] and dash [-] in the URI, following this pattern. I wonder if you can use the script we wrote for diacritics in search to help with this.
The script will need to do the following:

For each egesdh-version-0-1.xml/TEI/text/body/div[@type="entry"]/head/text() please create a URI by converting the tei:head text node to the following format

- Replace all diacritics with their basic ASCII equivalent, thus ḥ (h with dot under) becomes h, etc.
- Please do preserve upper and lower case in the URI and in this transformation
- Please replace all whitespace, punctuation, and any other non-alphanumeric characters [such as modifier letter left half ring ʿ and modifier letter right half ring ʾ ] with a dash
- The final result should end with an alphanumberic character not a dash
- The final result should not have more than one consecutive dash so please run a script to eliminated duplicates (for example, Bar ʿAli, Ishoʿ would become "Bar-Ali-Isho" not "Bar--Ali--Isho-")

I am open to any other suggestions about how to handle the commas and the half rings which would be nice to indicate even if just with a common symbol but I don't see how we can do it safely and I would like the URI to begin with the same letters for alphabetization as the entry.

The final result should be inserted back into  egesdh-version-0-1.xml/TEI/text/body/div[@type="entry"] right after the tei:head element in this path:

```
TEI/text/body/div[@type="entry"]/ab[@type="idnos"]/idno[@type="uri"] (see the egedshsample.xml file)
```
```
<div type="entry">
        <head>Bar ʿAli, Ishoʿ</head>
        <ab type="idnos">
                  <idno type="uri">http://gedsh.bethmardutho.org/Bar-Ali-Isho</idno>
        </ab>
```

fyi, there may be other non-alpha numerics besides half-rings and punctuation, but I am not aware of them, please let me know what else you encounter.

p.s. Please save this script as we may want a modified version to use with a diacritic free search function.

**Comment by davidamichelson** [comment]
Actually I have had another idea on this, please wait

**Comment by davidamichelson** [comment]
Okay, I updated this to create the URIs from the egesdh-version-0-1.xml file instead of the toc file.

Also, it turns out that George Kiraz may have a script for safe URI characters if you can't find one handy on the web and want to contact him.

**Comment by wsalesky** [comment]
First pass at URIs:
https://github.com/srophe/e-gedsh/tree/issue11

**Comment by davidamichelson** [comment]
Looks like the replacements of characters with diacritics did not work. For example: 
```
        <head>ʿAbdishoʿ bar Bahrīz</head>
        <ab type="idnos">
          <idno type="uri">http://gedsh.bethmardutho.org/Abdisho-bar-Bahrz</idno>
```

The ī (i with macron) should have been replaced with ascii "I" but has disappeared.

```
        <head>ʿAbdullāh I bar Sṭephanos</head>
        <ab type="idnos">
          <idno type="uri">http://gedsh.bethmardutho.org/Abdullh-I-bar-Sephanos</idno>
```

here the a with macron and the t with a dot under it have disappeared instead of being replaced.

```
        <head>ʿAbdullāh II Saṭṭūf</head>
        <ab type="idnos">
          <idno type="uri">http://gedsh.bethmardutho.org/Abdullh-II-Saf</idno>
```
Same here where t with dot and u with macron

**Comment by wsalesky** [comment]
Hum. Okay, perhaps I should contact George and see what he uses.

**Comment by davidamichelson** [comment]
@gkiraz could you share any regex or script with Winona on this please?

**Comment by wsalesky** [comment]
Updated version: https://github.com/srophe/e-gedsh/tree/issue11

**Comment by davidamichelson** [comment]
@wsalesky  perhaps did you forget to sync your local changes? This branch https://github.com/srophe/e-gedsh/tree/issue11 still shows the same errors from yesterday.

**Comment by wsalesky** [comment]
Hum, some tangled branches. Will have to sort them out tonight and update the data then. Sorry for the confusion!

**Comment by davidamichelson** [comment]
No problem.

**Comment by wsalesky** [comment]
Updated version, on untangled branch:
https://github.com/srophe/e-gedsh/tree/issue11

Let me know how they look. I looked through all the ones you listed and a few others and they look good to me.

**Comment by davidamichelson** [comment]
Okay the transformation worked, but now we need to wait to run the head replacements from issue #12 first because that will clean up some typos. I can explain shortly.

**Comment by davidamichelson** [comment]
Thank you by the way! great work!

**Comment by wsalesky** [comment]
No problem. I think I will run them all sequentially on a fresh file once we know they are working as expected.

**Comment by wsalesky** [comment]
updated on master

**Comment by wsalesky** [comment]
Marking as complete, let me know if you find any errors
