### ISSUE TITLE
Syriaca text boxes in margin

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#110]
Is this still under construction? Giwargis of Be'eltan has text box for Gewargis I.

I also have some general comments on this feature.

**Comment by wsalesky** [comment]
It is, but please share comments, and I will work them in as I go along. The feature will sort/goup by type (persons/places) and will list all persons/places found in the entry. Including persNames and placeNames with ref attributes and idnos with type='subject'

**Comment by dlschwartz** [comment]
Am I right that we can close this issue?
