### ISSUE TITLE
display of cross references in html

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#112]
The display of the cross references seems suddenly to have changed and now no longer resembles the print version closely enough.
Please make them less bold and bright.
More importantly, they should be regular font and NOT italics.

**Comment by dlschwartz** [comment]
@upossekel I was under the impression that you wanted these set off so that you could easily see them while proofreading. If this actually makes things harder, Winona can certainly make a change. There was never an intention to go live with what we have now. Please let Winona know when you would like this change made. Thanks.

**Comment by upossekel** [comment]
Please see my email on the subject, Dan. The web display of cross refs. was fine.

Winona, can you please make the display as it was before? In particular, cross references should NOT display as italics if they are not. Some headwords are in italics and I need to check for those. Also, it looks confusing if things are in italics that are not supposed to be. No need for the bold, either - but color-coding is great for the proofreading. Thanks

**Comment by dlschwartz** [comment]
@wsalesky Ute and I are discussing this issue at the moment. Having the cross-references inside articles display in both red text and it italics makes it more difficult for her to proofread the parts of the text that are supposed to be in italics, such as book titles in the bibliography, etc. Could we remove the italics from the display of ref rend="bold" target="[url]">? Thank you.

**Comment by wsalesky** [comment]
Please check now. Sorry about the delay in the response!

**Comment by dlschwartz** [comment]
Looks great. Thanks Winona!
