### ISSUE TITLE
display of subtitles in HTML

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#113]
It's great that they are more visible now, but perhaps the font can be slightly smaller, so as to bring it more in line with the print version? I also suggest to make the spacing such that the space to preceding paragraph of text is larger than the space to the following paragraph (for which it serves as subtitle).

**Comment by wsalesky** [comment]
I made the space above larger and the space below smaller, but left the text the same same size. Let me know if that is sufficient.
