### ISSUE TITLE
hyperlinks 

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#114]
When there are references to a website, how do we encode this in XML? They do not seem to work generally. Example, line 26186 and here, end of biblio.
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Guillaumont-Antoine&num=242

Please advise.

**Comment by wsalesky** [comment]
@dlschwartz ? How would you like to see this encoded in the XML?

**Comment by dlschwartz** [comment]
@wsalesky I thought we had decided that they way it is encoded at lines 26180-26183 was what we wanted ref type attribute with "url" and a target attribute with the web address. This seems to be working with the urls here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Bibliography (lines 12613 and following in the xml).

**Comment by dlschwartz** [comment]
@wsalesky Is this not working here because the web address has a typo? It should be http://www.college-de-france.fr/default/EN/all/ins_dis/antoine_guillaumont.html (with an "l" at the end) instead of http://www.college-de-france.fr/default/EN/all/ins_dis/antoine_guillaumont.htm. @upossekel Try fixing this and seeing if it works.

**Comment by wsalesky** [comment]
@upossekel did you add a ref element here? It should be picked up automatically. Please let me know if that is not happening.

**Comment by dlschwartz** [comment]
Neither link actually works, unfortunately.

**Comment by dlschwartz** [comment]
@wsalesky Ute and I are discussing this issue. It seems to still be a problem. Lines 14335 and following are encoded correctly with ref type="uri" target="[url]". This is not producing a hyperlink here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Chicago. There are other examples of this same problem. Please let us know if you need to see other examples. Thanks.

**Comment by wsalesky** [comment]
Fixed.

**Comment by dlschwartz** [comment]
Perfect
