### ISSUE TITLE
Author line on website

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#115]
Can we please not display the word 'author' before the name at the end of each entry? Encyclopedia articles usually just finish with the author's name and it is clear to everyone that this is the person who wrote it.
This is kind of a nuisance in proofreading, and I would appreciate if you can just take this out. I also think it's confusing.Thanks!

**Comment by dlschwartz** [comment]
I think it is a bit of an open question at the moment how we will display the author in the final version of the html. Before making final decisions I want to consult other digital encyclopedias and perhaps get George's input. If having the "author" text appear makes proofreading more difficult, @wsalesky can you please remove that? Thank you.

**Comment by dlschwartz** [comment]
This issue is duplicated elsewhere so I will close it here.
