### ISSUE TITLE
'false' cross references in print version

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#116]
It appears that there are a very few instances when items are printed in bold in print version, to indicate cross references, but there is no proper keyword for this item. 

Example: entry on Harqlean version has cross-ref. to Philoxenian version, but I see no such entry. How do you want to treat these?

Possible approaches include:
1. print in normal font
2. print in bold, but no link to a different entry
3. cross-reference to a similar item (e.g., biblical versions, or Philoxenus).

If we opt for 2. we would need a feature to format for bold font. This has been a need for some other reasons as well, and it would be good to have that soon.

**Comment by dlschwartz** [comment]
@upossekel I think we should simply make a note in the xml and ask George whether he would like that ref to point to something in particular or we should simply consider this an error in the print version. If there are only a few of these, this should be pretty easy to manage.
