### ISSUE TITLE
IDNOS: Importing data from gedsh-toc-and-idnos.xml into egesdh-version-0-1.xml

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#12]
After issue #11 is done, @wsalesky please prepare a script to import data from gedsh-toc-and-idnos.xml into egesdh-version-0-1.xml

The first task will be using document order to match up the entries in gedsh-toc-and-idnos.xml with the entries in egesdh-version-0-1.xml

Hopefully the 622 root/row/head elements in gedsh-toc-and-idnos.xml in document order match the div[@type="entry"]/head elements in document order in egesdh-version-0-1.xml 

Please do an initial comparison of the head elements in the two documents and check if they match. (Note: the text nodes will only match about 95%, sometimes the Headword in the TOC was slightly different from how it was printed in the actual article, we want to preserve both). 

If they do match then we need to insert data from gedsh-toc-and-idnos.xml  into the master document. If they don't let me know and I will try to sort it out manually.

As an added check please compare gedsh-toc-and-idnos.xml/root/row/author in document order against egesdh-version-0-1.xml/TEI/text/body/div[@type="entry"]/byline/persName. If they do not match please let me know.

Once they do match, here are the insertions I would like you to write.

Please insert them into egesdh-version-0-1.xml/TEI/text/body/div[@type="entry"]/div[@type="idnos"]/ab[1]/  AFTER egesdh-version-0-1.xml/TEI/text/body/div[@type="entry"]/div[@type="idnos"]/ab[1]/idno[@type="uri]

gedsh-toc-and-idnos.xml/root/row/bibl will become ```<idno type="syriaca-bibl">foo</idno>```

gedsh-toc-and-idnos.xml/root/row/entry will become  ```<idno type="entry">foo</idno>```

gedsh-toc-and-idnos.xml/root/row/pages will become ```<milestone unit="pages" n="foo"/>```

gedsh-toc-and-idnos.xml/root/row/head IF DIFFERENT FROM egesdh-version-0-1.xml//TEI/text/body/div[@type="entry"]/head will  ```<idno type="althead">foo</idno>```

gedsh-toc-and-idnos.xml/root/row/Alternate_Name, if present (and there could be multiple in the same row), will become  ```<idno type="althead">foo</idno>```

gedsh-toc-and-idnos.xml/root/row/subject, if present, will become  ```<idno type="subject">foo</idno>```
Note: One of these has two values in its text node but we can fix that manually later.

gedsh-toc-and-idnos.xml/root/row/type, if present, will become  ```<note type="type">foo</note>```

gedsh-toc-and-idnos.xml/root/row/abstract, if present, will become ```<note type="abstract">foo</note>``` Note: please preserve all XML inside these nodes as they have further mark up in them.

gedsh-toc-and-idnos.xml/root/row/Not_Useful, if present, will inserted inside the abstract as a tei:note thus egesdh-version-0-1.xml/TEI/text/body/div[@type="entry"]/div[@type="idnos"]/ab[1]/note[@type="abstract"]/ ```<note>foo</note>``` Note: these will be eliminated in a later editing stage, they are just for our reference.

gedsh-toc-and-idnos.xml/root/row/affiliation, if present, will become ```<note type="affiliation">foo</note>``` 

Note please don't insert these if the contents of the text node in gedsh-toc-and-idnos.xml is nul.

**Comment by davidamichelson** [comment]
I have updated the sample entry egedshsample.xml to reflect the transformation.

**Comment by davidamichelson** [comment]
I updated this to reflect that the URI will already be inserted from issue #11

**Comment by davidamichelson** [comment]
Okay, just a note to say that https://github.com/srophe/e-gedsh/issues/15 has one more related item, but it could be run on its own as well.

**Comment by wsalesky** [comment]
Initial run finds 32 non matching head elements. I will print a list.

**Comment by davidamichelson** [comment]
Great I will edit both the gedsh-toc-and-idnos.xml  and the egesdh-version-0-1.xml file based on the list and then ask you to run this again.

**Comment by davidamichelson** [comment]
Okay, I have updated both gedsh-toc-and-idnos.xml and egesdh-version-0-1.xml. Please add one more transform. 

First a note, the document order of both docs match, so that is fine.

The new transform is, if head element does not match between egesdh-version-0-1.xml and gedsh-toc-and-idnos.xml, please replace the head in egesdh-version-0-1.xml  with the version in gedsh-toc-and-idnos.xml.

Thanks,
D

**Comment by wsalesky** [comment]
Okay, just to be clear the new idno/notes should be inserted into every enter? And the entry/head should be updated in egesdh-version-0-1.xml?

**Comment by wsalesky** [comment]
Here is the first pass at this transform (includes data from #11):
https://github.com/srophe/e-gedsh/tree/issue12

**Comment by davidamichelson** [comment]
@wsalesky This issue and #11 and #15 appear all to be in order with one small change, because of the typos in the tei:head elements in the master branch version of egesdh-version-0-1.xml, we need to run the scrip that will replace them from gedsh-toc-and-idnos.xml first.

That script is  if head element does not match between egesdh-version-0-1.xml and gedsh-toc-and-idnos.xml, please replace the head in egesdh-version-0-1.xml with the version in gedsh-toc-and-idnos.xml.

I can explain at our meeting. Thanks!

**Comment by wsalesky** [comment]
Okay

**Comment by wsalesky** [comment]
Updated on master

**Comment by wsalesky** [comment]
Marking as complete
