### ISSUE TITLE
is the webpage down

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#121]
I can't access the html files. Is the page down?

**Comment by wsalesky** [comment]
@upossekel Sorry, the whole dev server is currently down. We are migrating to a new database install and are running into some issues, I will let you know when it is up.

**Comment by wsalesky** [comment]
@upossekel The site is back up. Webhooks are not yet operational. Hopefully by tonight.

**Comment by upossekel** [comment]
Please let me know when the webhooks function again, as I do need these. Thank you!
