### ISSUE TITLE
Script to insert Syriaca.org URIs

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#122]
Please write a scrip that does the following:

For each tei:ref/@target="http://gedsh.bethmardutho.org/..." in /TEI/text/body/div/div/@type="body" or /TEI/text/body/div/ab/note/@type="abstract" please add into the target the corresponding Syriaca.org URI

This Syriaca.org URI can be found by matching the http://gedsh.bethmardutho.org/... in the textnode of  /TEI/text/body/div/ab/idno/@type="URI" with the textnode of sibling /TEI/text/body/div/ab/idno/@type="subject" 

Thus in the article below http://gedsh.bethmardutho.org/Antioch = http://syriaca.org/place/10

```<head>Antioch</head>
                <ab type="idnos">
                    <idno type="URI">http://gedsh.bethmardutho.org/Antioch</idno>
...
                    <idno type="subject">http://syriaca.org/place/10</idno>
```

As an example on line 5315 of the Gedsh document the following should happen:

```
 is the Antioch of Shapur’, the later Gondeshapur (<ref rend="bold" target="http://gedsh.bethmardutho.org/Beth-Lapat">Beth Lapaṭ</ref>).
```
becomes
```
 is the Antioch of Shapur’, the later Gondeshapur (<ref rend="bold" target="http://gedsh.bethmardutho.org/Beth-Lapat http://syriaca.org/place/35">Beth Lapaṭ</ref>).
```
Note that http://syriaca.org/place/35 has been inserted.

Potential Issue: in the HTML of the article we do not want http://syriaca.org/place/35 to be a live URL on the http://gedsh.bethmardutho.org/Beth-Lapat should be live. If as we discussed it would be better to not double the @targets we can do that this way:

```
 is the Antioch of Shapur’, the later Gondeshapur (<ref rend="bold" target="http://gedsh.bethmardutho.org/Beth-Lapat"><placeName ref="http://syriaca.org/place/35">Beth Lapaṭ<placeName></ref>).
```
Also bonus challenge. Once the Syriaca.org URIS are in we would like to wrap the contents of tei:ref with persName and placeName anyway. So if your script can do that it would be a bonus.

Final note. Please run the script on a separate branch for now as we don't want to disrupt Ute's progress with extra data. We will take the results and just paste them into the Antioch article http://gedsh.bethmardutho.org/Antioch on dev so we can see it.

**Comment by wsalesky** [comment]
First run, available on branch issue122

**Comment by davidamichelson** [comment]
Thanks! Please don't merge this branch as we don't want to disrupt Ute's work. Instead, @dlschwartz could you please paste into the master branch just the entry for Antioch from this issue 122 branch as we can use it as a test record.

@wsalesky please save this script somewhere and link to it here so we can run it on the whole when we are ready.

**Comment by wsalesky** [comment]
Script: 
https://github.com/srophe/e-gedsh/blob/master/processing/add-urls.xql

**Comment by dlschwartz** [comment]
Sorry of the delay. I have cut and pasted as Dave suggested.

**Comment by davidamichelson** [comment]
Although, actually I think I mispoke and meant merge, did you overwrite the
URIS you had added by hand?

**Comment by dlschwartz** [comment]
I thought you wanted me to cut and paste the whole entry for Antioch so that's what I did. So yes, I overwrote the URIs I had added by hand. However, I believe Winona wrote the script so that if a syriaca URI is present the script does not overwrite or add another. It looks to me like the one's I added by hand have not been changed.

**Comment by davidamichelson** [comment]
Great!

**Comment by wsalesky** [comment]
Did this get overwritten? I'm testing the RDF box on Aba I and returning 0 results for additional Syriaca.org links. 

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Aba-I

**Comment by dlschwartz** [comment]
Did we add URIs to Aba I? I know I put a bunch into the Antioch entry: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Antioch

The RDF box only seems to be grabbing the URI for the headword and not for the other URIs.

You should be able to test on Antioch and I'll look into Aba I.

**Comment by wsalesky** [comment]
Ah, that is where I went wrong... wrong entry.
Thanks!

**Comment by dlschwartz** [comment]
Yeah, I looked into Aba I and couldn't find a record of adding URIs there. Very good.

**Comment by dlschwartz** [comment]
@wsalesky I believe we are ready to revive this issue. Could you please run the script that should add syriaca.org URIs to all of the cross-references in the body of e-GEDSH entries? FYI, The appropriate syriaca.org URIs already exist as idnos in ab type="idnos" for each entry.  We don't want to add those again, of course, but we rather just in the body of the entries. Please let me know if you have any questions. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz New data here:
https://github.com/srophe/e-gedsh/tree/issue122-alt

Please review and then merge if it looks good to you. 
Thanks.

**Comment by dlschwartz** [comment]
@wsalesky I believe this is resolved. I'll close it.
