### ISSUE TITLE
problems with syncing

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#123]
this is about the problem with the line 'secondary literature' not being in larger font in print version and thus not formatted in XML as 'head'. Marking with 'choice' did not work and recent edits to Master did show in my file but have cause problems so that I cannot sync the file.
Line 46024.

**Comment by wsalesky** [comment]
@upossekel can you please clarify? I took a look at the webhooks and they do not report any errors, so the issue could be with display, not syncing. 

It would be helpful if you could paste the xml block you are having trouble with right here in the issue, and explain what you expect to see online and what you actually see.

**Comment by upossekel** [comment]
This issue is that I cannot sync. I undid the edits by Dan about the choice and head elements (to be dealt with later), and file seemed to be okay. Nevertheless, it does not sync even if there is no error in XML.  Then I produced a back-up version so as not to loose most recent work, but evidently that might have created further problems. Deleted that file, but still no solution.

**Comment by dlschwartz** [comment]
@upossekel Can you skype right now. If you have Oxygen open and can share screen we should be able to figure this out.

**Comment by wsalesky** [comment]
@upossekel Does, "can't sync" mean you can not save to github (you get an error, and if so what), or that you do not see your changes on the website?

**Comment by upossekel** [comment]
Yes, trying to reset skype password.

 

Ute

**Comment by dlschwartz** [comment]
@wsalesky Ute uses the desktop Github program to commit and sync. When she tries to sync this her latest changes, she gets the following message:
"Failed to sync to this branch. You might need to open a shell and debug the state of this repo."
I have no idea how to do this. Could you please take a look at this for us? Thanks!

**Comment by wsalesky** [comment]
@dlschwartz do you want me to replace:
egesdh-version-0-1.xml
with 
egesdh-version-0-1.xml_8 May 2017

and then resync?

**Comment by wsalesky** [comment]
@upossekel @dlschwartz 
Can @upossekel save her changes outside the repository and then run 
git reset --hard HEAD

in the command line in the root directory for her repository? (This will set the local repository to the same state as the remote, and should help resolve any issues that may have been introduced.) Then you can try moving the changes back in.

**Comment by dlschwartz** [comment]
@wsalesky Yes, that is what we will do. Thanks.

**Comment by wsalesky** [comment]
@upossekel @dlschwartz Let me know how it goes.

**Comment by dlschwartz** [comment]
@wsalesky I'm still not exactly certain what went wrong. It was most likely a merge conflict of some sort. But everything is resolved now.

Everything except the web hooks. Ute's most recent changes are not appearing in the html. Could you please take a look at those and then we can close this issue. Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz how about now?

**Comment by dlschwartz** [comment]
@wsalesky Looks great. Thank you!
