### ISSUE TITLE
html letter J does not open up

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#126]
When clicking on letter J in left-hand bar of html, an error message occurs.

This is where I end up when clicking 'J' on left hand bar.

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?fq=;fq-Browse:N;fq-Browse:N;fq-Browse:O;fq-Browse:O;fq-Browse:I;fq-Browse:J&id=http://gedsh.bethmardutho.org/Old-Syriac-documents 

However, if I go to O and then Old Syriac Documents, that entry opens up properly.

I can also get to the J entries by clicking forward from I (or backward from K), but what does not work is the J in alphabetical list.

**Comment by wsalesky** [comment]
Note to self: possible cause not clearing other browse param?

**Comment by wsalesky** [comment]
Fixed
