### ISSUE TITLE
entry on Smith does not open up in html

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#127]
The entry on Smith brings up an error message only.

here is the link
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Smith-Agnes-and-Margaret&fq=;fq-Browse:N;fq-Browse:N;fq-Browse:O;fq-Browse:O;fq-Browse:S;fq-Browse:S

**Comment by wsalesky** [comment]
@upossekel  Please include links in the issue. Thanks!

**Comment by wsalesky** [comment]
Fixed.
