### ISSUE TITLE
CASRAI CREDIT TAXONOMY

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#13]
@dlschwartz This might be a good (and relatively simple) project to try inserting the CASRAI Credit Taxonomy in the respStmt. Any thoughts?

**Comment by dlschwartz** [comment]
Sorry for the slow reply. Agreed. I'll think about this.
Dan

On Fri, Sep 23, 2016 at 6:51 PM, David Michelson <notifications@github.com>
wrote:

> Assigned #13
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_e-2Dgedsh_issues_13&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=_AR0P7KO94_7JUTLetMPh70g8m6JZNKfp9st2AUrI08&s=Qzd_V0G81T6AzMkVsChf9sKVFr3eiX3fEVPNxldLb70&e=>
> to @dlschwartz
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dlschwartz&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=_AR0P7KO94_7JUTLetMPh70g8m6JZNKfp9st2AUrI08&s=0WHRQLBe-hNOFSZ8Jak87lpZMS_gfMRZUond8yVWeKg&e=>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_e-2Dgedsh_issues_13-23event-2D801093141&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=_AR0P7KO94_7JUTLetMPh70g8m6JZNKfp9st2AUrI08&s=DJuj5s9mR6XLGWXMn_kkfPZnHjCBgN_7HN20cMCaAMc&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzo2Mzo1QS3qXqcjtoRU6FuoeEXh0ks5qtGYYgaJpZM4KFfU7&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=_AR0P7KO94_7JUTLetMPh70g8m6JZNKfp9st2AUrI08&s=lHZjUKPkg-XXTsFArI4bBVs7Qv3Cwe9_ti_Kb8d1qoY&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by dlschwartz** [comment]
@davidamichelson I think we should just close this issue and drop CASRAI for GEDSH. Let's start with what we have already and get GEDSH out the door rather than try implementing this right now. What do you think? Close the issue if you agree. Thanks.
