### ISSUE TITLE
are webhooks working?

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#130]
The changes that I implemented some days ago are not in the html. Can you please check if the web hooks are working? Thanks!

**Comment by wsalesky** [comment]
I loaded it manually for you. It may have been caused by the server downtime.

**Comment by upossekel** [comment]
Thank you; unfortunately the changes still don't show. I sync'ed again but still the same.

**Comment by upossekel** [comment]
Example: entry on Shubhalmaran: cross-reference to Barhadbeshabba in first paragraph.
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Shubhalmaran&fq=;fq-Browse:S
XML line 51445.

**Comment by wsalesky** [comment]
There was an unclosed title element, line 55268 that prevented the file from loading. I corrected it and pushed it back to github. Do you see your changes now?

**Comment by wsalesky** [comment]
Great. Don't forget to get the latest version from github before doing more editing.
