### ISSUE TITLE
can we display front and back matter and captions in html

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#134]
I wonder if it would be easy to display in html the front matter, back matter, and image caption. That would really help with the proofreading!

For now, I've displayed the 'author view' in Oxygen and read that against the print version. However, the italics don't show and it's really hard to make sure one does not miss any.

Thanks!

**Comment by wsalesky** [comment]
@upossekel  As separate entries? I think it should be possible. How urgent would this be?  @dlschwartz

**Comment by upossekel** [comment]
Would be good to have this sooner rather than later. They can be long files: one for captions, one for front matter, one for back matter; or broken down into logical section. No need to have them all individually. HTML allows for better checking for formatting/typos.
