### ISSUE TITLE
paragraph/line breaks in image captions?

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#136]
Do you want any paragraph breaks in image captions? The print version has captions centered (personally, I don't think this looks good), and I'm not sure if there was any rationale as to where the lines ought to break. For now I'll leave it as one paragr. per caption, but can edit if you wish.

**Comment by dlschwartz** [comment]
For the time being, let's just make sure I put the text in correctly and then we'll get sorted on display. Thanks.

**Comment by upossekel** [comment]
Right. Just wanted to add it to your ‘to-do’ list before I forget.

**Comment by dlschwartz** [comment]
@upossekel I'm trying to check eGEDSH issues off the list. Please take a look at formatting of images captions here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/fig/1. You can move through them using the blue arrows next to the URI. If you are happy with this formatting, please go ahead and close this issue in Github. Thanks.
