### ISSUE TITLE
Can we have front and back matter in HTML?

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#138]
It would be very helpful for proofreading the XML of front and back matter if we could have an XML for this. It could perhaps be treated as if it were an entry (or several), for formatting purposes. I'm hoping to finish this by Wednesday and would really appreciate help with that.

Thank you!

**Comment by wsalesky** [comment]
Here you go: 
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=front
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=back

I am sure there are some things that need to happen to the xslt (HTML display of elements). You can post them in the issues list and I will work on them as I can, but I will be out for the rest of the week.

**Comment by wsalesky** [comment]
We will need to discuss how to access these, via browse and search, they are not currently included in either of these functions.
