### ISSUE TITLE
we need more types of heading and subheadings

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#139]
We need to introduce different levels of headings. There are chapter titles, e.g., 'Maps' n p. 471. Then there subtitles (that don't stand out very much, e.g., I. Syriac Christianity etc. on p. 471). The list of patriarchs has various levels of subheadings.

E.g., on p. 481 'List of patriachs etc.' is chapter title;
I. The Church of the East etc. is subtitle
'Main secondary sources is subheading.

**Comment by wsalesky** [comment]
I added some size differences for the various headings/subheadings let me know if this is not enough, I can make it more dramatic. (Note if you are using Chrome you may need to do a hard refresh in the browser to see the new styles. )
