### ISSUE TITLE
Is there an English spell check we could run on the body paragraphs?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#14]
There are several places where there are hyphens that need to be deleted, but there are also hyphens that are integral parts of the text. Any ideas on how we could delete them safely?

I suppose we could look at an earlier version of the XML and check for them at the end of lines and then match?

**Comment by wsalesky** [comment]
There is a spell check in oXygen, however this could be a laborious task considering how many non English words are in the file. We would probably be better off doing a find on all words with hyphens and checking them manually. I think we can  use regex in the oXygen search function.

**Comment by davidamichelson** [comment]
Thanks, I'll leave this to @dlschwartz to take the lead on. One option could be to pull out all hyphenations run spellcheck to fix them and then re-insert the results using the original as a key?

**Comment by dlschwartz** [comment]
Can you give me a bit of context here? The hyphens that need to be deleted
are hyphens appearing at the end of lines in the original wrapping of the
print text, is that correct? I'm not sure what you mean Dave in your latest
post. I would have thought that the type of manual process Winona mentions
would be the best bet. I'm not really sure how to use regex for this
Winona. Some help would be great though as there are almost 4500 hyphens in
text nodes. Thanks.


On Mon, Sep 26, 2016 at 8:20 AM, Winona Salesky <notifications@github.com>
wrote:

> There is a spell check in oXygen, however this could be a laborious task
> considering how many non English words are in the file. We would probably
> be better off doing a find on all words with hyphens and checking them
> manually. I think we can use regex in the oXygen search function.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_e-2Dgedsh_issues_14-23issuecomment-2D249567174&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=L2a60AnXB9MberxA1NOjt6CfOqopwjKB6Yqg5g5F2ZQ&s=aFMtqh7qI0wf_Nzc81GELolgxkxykcWrr4I8VMUIjoc&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzvBzNioHNMkwj-5F-2D8gV7vrPazl1Ajks5qt8aDgaJpZM4KFf-2Dj&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=L2a60AnXB9MberxA1NOjt6CfOqopwjKB6Yqg5g5F2ZQ&s=avXnn-4p0avxdbvPUan7iiLOAlyZ6b0kq5cgnPv_15k&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by davidamichelson** [comment]
Let's just discuss on Tuesday and I'll catch you up.

**Comment by davidamichelson** [comment]
Nevermind this was solved by George in the initial clean up!

**Comment by davidamichelson** [comment]
So there was a soft hyphen after all Unicode Character 'SOFT HYPHEN' (U+00AD) I deleted it.
