### ISSUE TITLE
table layout needed in html

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#140]
The list of patriarchs is in table format. Can you please render it in html, or explain exactly how this is coded, so that I can proofread? I have done the names and dates, but not the layout per se.

**Comment by wsalesky** [comment]
Can you clarify? Tables should use the tei:table element. If it is encoded using the following format, it should render as an HTML table.

Example TEI code: 
```
<table cols="2">
                        <row>
                            <cell>Yuḥanon Maron</cell>
                            <cell>
                                <date>ca. 685 – ca. 707</date>
                            </cell>
                        </row>
</table>
```
Are you not seeing this where you expect to?

**Comment by upossekel** [comment]
Yes, I think this is fine. Displays in html as table now. Thanks!

**Comment by dlschwartz** [comment]
Sorry, it's been a busy morning. It looks like you all got this sorted. Where is the html? I'd like to see this. Thanks.

**Comment by dlschwartz** [comment]
Nevermind, I have it now.

**Comment by wsalesky** [comment]
@upossekel @dlschwartz 
Can this be closed?

**Comment by dlschwartz** [comment]
Yes, thanks!
