### ISSUE TITLE
non-breaking spaces

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#142]
Regarding the issue of non-breaking spaces, I've searched online and found &#160 as non-breaking space. Please let me know how to type it into the text - just using these characters did not meet with success - and how to define a shortcut action.

**Comment by wsalesky** [comment]
The correct encoding is ` &#160;` I don't know about shortcut actions in oXygen, I have not used them. Perhaps @dlschwartz can help with that?

**Comment by upossekel** [comment]
Thanks! So would I just type that between the two words? I seemed to get an error message but will try again this afternoon.

**Comment by dlschwartz** [comment]
I've tested it and it seems to work fine. Let me know if there are any questions.

**Comment by wsalesky** [comment]
@upossekel @dlschwartz 
I think this has been resolved. Reopen if I am mistaken.
