### ISSUE TITLE
changes to XML in back matter don't display in html

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#143]
The changes I made yesterday to the xml file don't display in the html. Could someone please take a look and see if the web hook is working? This would be somewhat urgent so I can finish. Thanks!

**Comment by wsalesky** [comment]
Can you ping Dan on this? Ask him to check that is well formed and if he can try committing a minor change, that may force the webhooks into action if they failed due to poor xml formatting.

**Comment by dlschwartz** [comment]
@upossekel I'm just back at my computer now. Is there any chance you have resolved this. I do not know what you are expecting to see but not finding. The XML is well-formed though so the web hooks should be working. Do keep in mind Ute that the most important thing is clean text and that display of front and back matter has barely been discussed.

**Comment by dlschwartz** [comment]
@wsalesky The document is well-formed. I have been playing around with things regarding #125 and the changes do not show up in html. This is in the body, not the back. Minor changes in the back don't show up either. I'm wondering if the document is just too big? I hate to need you to intervene so often in general. But now that we're down to many little tiny tweaks, it's really a shame. Do you have any thoughts on this?

**Comment by upossekel** [comment]
Well, the document has not got much bigger, has it? Adding front and back matter is not that many lines overall. Could it just be stuck in the system somehow? Would be great to get this sorted. Thanks!

**Comment by wsalesky** [comment]
Hi all, I actually left my laptop at home, a vacation first, so there is not much I can do from here. Dan you have log in to the dev server, I can send you instructions on how to load the data manually via email.

**Comment by dlschwartz** [comment]
That sounds great. And well done going on vacation without your laptop! We should all follow your example. And soon.

**Comment by wsalesky** [comment]
Hi All, sorry for the delay, the new changes should be up on the dev server now, and the webhooks are back up also. 

Thank you for your patience.
