### ISSUE TITLE
front matter - display of page numbers

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#144]
We should think about how to indicate page numbers in the front and back matter. The current display is perhaps not ideal.

**Comment by dlschwartz** [comment]
Agreed. Thanks for making this note (and please feel free to use Github to do this). I'll be going through our outstanding Github issues and making a discussion list for our meeting with George, etc.

**Comment by dlschwartz** [comment]
We are not displaying page numbers in the digital edition.
