### ISSUE TITLE
Can we please delete in html the 'author' word that occurs with every byline?

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#146]
Two aspects here. First, it looks odd to have the word 'author' precede the author's name at the end of every single entry. This is surely not how it appears in the print version, and that this indicates the author is pretty obvious.

Moreover,  in front and back matter, this leads to strange display issues, for example at the beginning of the list of patriarchs.  p. 481 in back matter;  line 61936 in XML.

**Comment by dlschwartz** [comment]
@upossekel I think the jury is out on this one. I think Dave and I have both expressed a preference for the layout as it on this. If you feel strongly about this, we can certainly discuss this with the print editors. I trust a consensus will emerge.

**Comment by dlschwartz** [comment]
Yes indeed. The appearance of these in the front matter clearly does not work. Thanks.
