### ISSUE TITLE
text missing from footnotes in back matter

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#149]
In the html, e.g., p. 484, the footnote text does not display the entire text. Parts of the bibliographic citations drop out. XML line 62438 ff. 
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=back

For example, the XML has
 ```
>Rabban Hormizd</placeName> (successors of <persName>Bar Mama</persName>, 
<date>1551–1804</date>)<note n="2" rend="footer">For a recent discussion of the patriarchs/catholicoi during the five centuries of division within the Church of the East, see
<bibl>Murre-van den Berg, ‘The patriarchs of the Church of the East’</bibl>. For the confusion that has existed in scholarship  concerning the dates and numbering of Eliya VI and VII, see <bibl>S.
  P. Brock, ‘East Syriac pilgrims to Jerusalem in the early Ottoman period’, <title rend="italic">ARAM</title> 18–19 (2006–2007), Appendix (198–201)</bibl>. For the period
 between the <choice><sic>mid–16th</sic><corr>mid-16th</corr></choice> and the early 19th <abbr>cent.</abbr>, see also <bibl>A. Lampart,   <title rend="italic">Ein Märtyrer der Union mit Rom. Joseph   I. 1681–1696. Patriarch der Chaldäer</title> (1966), esp. 365–66</bibl>.</note></head>
```

The text in html reads: 
The Patriarchate of Rabban Hormizd (successors of Bar Mama, 1551–1804)
For a recent discussion of the patriarchs/catholicoi during the five centuries of division within the Church of the East, see . For the confusion that has existed in scholarship concerning the dates and numbering of Eliya VI and VII, see ARAM. For the period between the mid-16th and the early 19th cent., see also Ein Märtyrer der Union mit Rom. Joseph I. 1681–1696. Patriarch der Chaldäer.

**Comment by wsalesky** [comment]
Can you include the text I need to look for? It makes it easier to fine. (Just copy and past from the HTML.)

**Comment by wsalesky** [comment]
Okay. Missing text is now showing up.
