### ISSUE TITLE
Adding a althead with different word order for use is Named Entity Recognition

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#15]
@wsalesky Here is an additional transformation we would like to run on the tei:head data to generate names for use in NER.

For each /TEI/text/body/div[@type="entry']/head that contains a "," (comma) please add to that entry a /TEI/text/body/div[@type="entry']/ab[@type="idnos']/idno[@type="althead' @subtype="altorder"] where the head has been reordered in this manner, tokenizing on the comma:

Example: Bar ʿAli, Ishoʿ would become Ishoʿ Bar ʿAli, in regex terms this would be: (\w+?),\s(\w+?) becomes \2 \1 (p.s. I am not sure if \w+? is right?)

Example:
```
div type="entry">
            <head>Bar ʿAli, Ishoʿ</head>
            <ab type="idnos">
                 ...
                <milestone unit="pages" n="53-54"/>
                <idno type="althead" subtype="altorder">Ishoʿ Bar ʿAli</idno>
...
```

A few notes: 
1. Please insert this new idno[@type="althead' @subtype="altorder"] immediately after the tei:milestone element. There should be one in every ab[@type="idnos'] so that will be easy to find.
2. I believe there is only one tei: head that has more than one comma (``` <head>Vaschalde, Arthur Adolphe, C.S.B.</head>```). You could exclude it from your script and we can do it by hand. Please leave this issue open so that we do that.
3. I updated the egedshsample.xml to reflect this model

**Comment by wsalesky** [comment]
Added this to branch 12 as it uses the same base data, and needs to be run either concurrently with #12 or after changes #12 are made:

https://github.com/srophe/e-gedsh/tree/issue12

**Comment by wsalesky** [comment]
updated on master

**Comment by wsalesky** [comment]
Marking as complete
