### ISSUE TITLE
table size in list of patriarchs

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#150]
It might be good to have the same table size for all subsections in the list of patriarchs. Currently the spacing (column width) varies.

**Comment by upossekel** [comment]
It would be helpful for readers is the space between patriarch's name and the dates were of intermediate length: big enough to accommodate longer patriarchal names in left column, but not so far as to make it difficult to see which date goes with what name.

**Comment by wsalesky** [comment]
Take a look now. Is it better?
