### ISSUE TITLE
formatting of manuscript index

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#151]
Can the manuscript index in back matter, p. 535 ff.
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=back

be formatted to have indentation similar to printed volume. As is, it will be rather hard to use.

**Comment by dlschwartz** [comment]
@upossekel This one is for me. I threw this together too quickly. I will need to change the encoding of the location and archive from a p element to a label type="archive". Then @wsalesky should be able to visualize this like it is in the print edition.

**Comment by upossekel** [comment]
Sounds good, thank you.

**Comment by dlschwartz** [comment]
@wsalesky I changed the tagging for the manuscript section so that the name of the archive is wrapped in label type="archive". It now follows the same formatting as the labels in the body of the text which I think looks good. It would be nice though if we could have the shelf marks indented a little bit. This would help things stand out and bring things in line with the print edition, which I think is good. Please let me know if you have any questions. Thank you!

**Comment by wsalesky** [comment]
@dlschwartz Did this new version get pushed to github? I don't see the changes.

**Comment by dlschwartz** [comment]
Yes. At line 63713, for example, you should see a label type="archive". Here's the commit: https://github.com/srophe/e-gedsh/commit/563a7953f274b5ea4a0dcdf4b335695e40afcb83. Let me know if there are any questions about what I've done here. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz I think it would make more sense to put the label in the tei:p element.

**Comment by dlschwartz** [comment]
@wsalesky tweaked a couple of the divs and this seems to work very well. Thanks. I'll make the change throughout.

**Comment by dlschwartz** [comment]
@wsalesky This works well for getting the archives with only one shelfmark onto a single line. However, does this make it more difficult to indent the shelfmarks when we have multiple shelfmarks. I think it would be nice to set them off a bit in this way. Can we indent anything that is a p/idno and leave left adjusted anything that is a p/label? Thanks Winona.

**Comment by wsalesky** [comment]
Sure.

**Comment by dlschwartz** [comment]
Also, there seems to be extra space between the p/label and the p/idno. I would prefer to have this spacing the same as the spacing between the lines of p/idnos but greater spacing between each of the divs. Thanks.
