### ISSUE TITLE
index of manuscripts - space after colon

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#152]
Each manuscript number is followed be a colon, then come the page numbers. Can we format so that there is a space after the colon? Or should this be inserted into XML?

**Comment by wsalesky** [comment]
What does the XML look like?

**Comment by upossekel** [comment]
Like this:

<p>Baghdad, Chaldean Monastery</p>
                    <p><idno type="shelf">General:</idno><idno type="pgInGEDSH">51</idno></p>
                    <p><idno type="shelf">25 [= Alqosh 16]:</idno><idno type="pgInGEDSH">78</idno></p>
                    <p><idno type="shelf">509 [= Alqosh 169]:</idno><idno type="pgInGEDSH">388</idno></p>

HTML displays as
Baghdad, Chaldean Monastery

General:51

25 [= Alqosh 16]:78

509 [= Alqosh 169]:388

**Comment by wsalesky** [comment]
@upossekel  Please add it to the XML.
