### ISSUE TITLE
formatting of short titles

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#153]
These should be displayed such that the short title, followed by =, and the full bibliographic information forms one entity), similar to how it is in the print, p. xx ff.
I.e., second and following lines are indented; text after = does NOT begin on a new line but follows on the same line.
There should not be bullet points.
The formatting from the bibliographic entries to the articles can probably be used here.

**Comment by wsalesky** [comment]
Sample XML please?

**Comment by upossekel** [comment]
XML looks like this:

<p>Abbeloos and Lamy, <title rend="italic">Gregorii Barhebraei chronicon
                            ecclesiasticum</title> = <bibl>J. B. Abbeloos and T. J. Lamy, <title
                                rend="italic">Gregorii Barhebraei chronicon ecclesiasticum</title>,
                            1–2 (3 vols.; 1872–1877).</bibl></p>
                    <p>Abūna, <title rend="italic">Adab</title> = <bibl>Ab Albīr Abūna, <title
                                rend="italic">Adab al-lugha al-ārāmiyya</title> (1970).</bibl></p>

 

The html is like this:

 

Abbeloos and Lamy, Gregorii Barhebraei chronicon ecclesiasticum = 

*  J. B. Abbeloos and T. J. Lamy, Gregorii Barhebraei chronicon ecclesiasticum, 1–2 (3 vols.; 1872–1877).

 

Abūna, Adab = 

*  Ab Albīr Abūna, Adab al-lugha al-ārāmiyya (1970).

 

The bullet points should not be there, I think.

One entry would be for each author, thus no line break after the =.

 

Thanks!

**Comment by dlschwartz** [comment]
@wsalesky When I did the initial encoding on this material, I didn't do a lot with it.  It's at lines 1411-1651. I think we can simply follow the layout in the print edition here. The examples given by @upossekel would then look like this but they would also have a hanging indent:

Abbeloos and Lamy, Gregorii Barhebraei chronicon ecclesiasticum = J. B. Abbeloos and T. J. Lamy, Gregorii Barhebraei chronicon ecclesiasticum, 1–2 (3 vols.; 1872–1877).
Abūna, Adab = Ab Albīr Abūna, Adab al-lugha al-ārāmiyya (1970).

Hopefully that helps.

**Comment by wsalesky** [comment]
@dlschwartz has this been resolved?

**Comment by dlschwartz** [comment]
No. And what was I thinking when I put this into the document. I made a mess of things. I will have to do this again. The div with <idno type="URI">http://gedsh.bethmardutho.org/Frequently-Cited-Publications-Author-Short-Title</idno> should simply be a listBibl containing individual bibls for each entry. I'll do that now.

**Comment by dlschwartz** [comment]
Okay, this section should produce a much better result now (what was I thinking!). It should be formatted just like the listBibls in the entries, single spaced with a hanging indent. Thanks Winona.

**Comment by dlschwartz** [comment]
This looks great. Thanks. I'll close this issue.
