### ISSUE TITLE
Can we have the captions of plates in HTML?

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#154]
I don't think this is part of the files I've got. Could we please have html of the captions? It will facilitate the final check.

**Comment by wsalesky** [comment]
@upossekel What is the XML for the captions?

**Comment by dlschwartz** [comment]
The captions for the images that appear in the body of the text of the print edition (i.e. not the Color Plates appendix on pages 451-480 which appear in lines 61642-61803 of the main document) are in a separate xml file: https://github.com/srophe/e-gedsh/blob/master/data/tei/e-GEDSH_figs.xml. 

I'm think it will be best to wait on this @upossekel until after we meet with the editors of the print edition (I'll be setting up a meeting shortly, you can keep an eye out for the email). We're not actually sure if anyone actually has the images. What we do with this material will likely vary considerably based on whether or not we are able to put images online. 

Let's keep this issue open for the moment but not build anything yet. Thanks.

**Comment by upossekel** [comment]
It would just be really helpful to have the HTML for this, so that I can finish up with the proofreading of these captions. A lot of the images should be available easily, since quite a few are personal photographs. We just would need to get consent from owners, which should not be a problem.

**Comment by dlschwartz** [comment]
@upossekel, please just proofread the text in the xml. It does not make sense to build this until we have the images. I will ask the group of print editors if they have them but when I last asked, George did not have them. This is a group effort and once it makes sense for Winona to build this I can do the initial checking on the html and they you can sign off. Thanks Ute.

**Comment by upossekel** [comment]
I went through the XML and corrected where needed. But there where a lot of issues and likely something got overlooked. We just need to make a note that this needs to be double-checked.

**Comment by dlschwartz** [comment]
@upossekel @wsalesky I propose we close this issue and once we reach a final status regarding the images  (whether or not we'll be able to include them -- we also need to sort out permissions!) we can decide how to proceed with the visualization. Ute, could you please create a different issue that details your concerns with the current text as encoded in the xml. Please assign that to me and I will then be able to follow up on these at the appropriate time. Thank you.
