### ISSUE TITLE
footnote placement and bibl element

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#156]
In line 63353, the footnote is placed within the bibl element.

bibl>R. J. Mouawad, <title rend="italic">Les Maronites. Chrétiens du
                                Liban</title> (Fils d’Abraham, 2009), 231–46.<note n="12"
                                rend="footer">The present list is largely based on Mouawad’s work,
                                which incorporates Maronite scholarship from the time of al-Duwayhī
                                to the present day (see the bibliography on p. 224). For most
                                patriarchs the name is followed by the place of
                            origin.</note></bibl>

(This was the case also for footnotes following headers; they were within the header element. This resulted in the footnote text not being properly displayed. So I moved footnotes AFTER the header element. It worked fine.)

With bibl element, however, an effort message occurs. This may have to do with the syntax.

**Comment by dlschwartz** [comment]
@upossekel In general, the note element should go inside the relevant element as it is a part of that entity. It is part of a bibl just as it would be a part of a p element. If there is a problem with the visualization in html, we'll need to let Winona know so that she can fix that in the app.

**Comment by wsalesky** [comment]
What is the error? Is when you save it or when you try to view the HTML?

**Comment by upossekel** [comment]
Yes, you will need to look into that. If footnote is inside it does not format correctly. As of now, I’ve moved all footnotes outside the bibl element (there are only a few in back matter, in the list of patriarchs), so we would have to revert that. Should not take long.

**Comment by dlschwartz** [comment]
Yes, please revert the notes in bibl. Remember that markup and display are separate (though related). The note is a part of the bibl element and ought to be included in it. Thanks Ute.

**Comment by upossekel** [comment]
Okay, if you think it’s part of the bibl element. In my thinking, it is actually *not* part of the bibl element but something additional to it.

**Comment by wsalesky** [comment]
I have added handling for footnotes. It may need some more work. Please add a new ticket if you find bugs with the current implementation.

**Comment by dlschwartz** [comment]
This looks good but will likely need some tweaking after we wrestle with https://github.com/srophe/e-gedsh-app/issues/17. Thanks!
