### ISSUE TITLE
attribute for small caps

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#157]
Can we have an attribute for 'hi' that is for small caps?
I guess it would be like `<hi rend=small-caps>`.

In the list of patriarchs, the titles are only partially printed in small caps, so the attribute can here not just be added to the head element. Or we can override the print version and make the entire header line into small caps.

Please advise.

**Comment by dlschwartz** [comment]
@upossekel Go ahead and use hi rend="smallCaps" and we can decide how to visualize this.

**Comment by wsalesky** [comment]
It should visualize automatically. If not, let me know.

**Comment by wsalesky** [comment]
@dlschwartz  @upossekel Is this rendering correctly now?

**Comment by dlschwartz** [comment]
@wsalesky It is not because @upossekel did not implement it. It won't validate unless I update the schema to allow small-caps as an acceptable value for the rend attribute. I'll do that now and make the changes in the TEI.

**Comment by dlschwartz** [comment]
The small-caps is working fine now but the bold is not. See line 62538, 
<hi rend="bold small-caps">The Patriarchate of 
<placeName ref="http://syriaca.org/place/168">Rabban Hormizd</placeName></hi>

**Comment by dlschwartz** [comment]
```
<hi rend="bold small-caps">The Patriarchate of <placeName ref="http://syriaca.org/place/168"
                                >Rabban Hormizd</placeName></hi>
```

**Comment by dlschwartz** [comment]
Actually, @wsalesky, a better example for why this is desirable can be found here at line 62662 
`<head type="subsection"><hi rend="bold small-caps">The Uniate Chaldean Patriarchate of Babylon</hi> (Mosul, Baghdad,
                            <date>1830 to date</date>)</head>`

**Comment by upossekel** [comment]
It worked find for the subtitles beforehand; now they don’t display as small caps (but perhaps that was changed by someone). Also, in the front matter the small caps don’t show in the second paragraph on p. X. (Here it is the page numbers).

 

Or did the webhook not work for this?

 

This is the XML:

= New Testament), churches (<choice><sic>e.g.</sic><corr>e.g.,</corr></choice>
                    Melk. = Melkite), etc. These abbreviations are explained on p. <hi rend="small-caps">XVII</hi>. In
                    addition, frequently quoted publications are referred to by the author’s last
                    name and a short title (full references are found on p. <hi rend="small-caps">XX</hi>–<hi rend="small-caps">XXII</hi>).</p>

**Comment by wsalesky** [comment]
I think this has been resolved. Please reopen if not.
