### ISSUE TITLE
NER for tei:ref [@type="cr"]

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#16]
@wsalesky 

After issue #15 is complete we would like to try and use our existing NER workflow in the following manner:

We would like to insert GEDSH URIS into all tei:ref [@type="cr"] as @target of the tei:ref.

The matching should proceed in this order.

First try to made the the contents of each tei:ref[@type="cr"]/text() with the headwords found in /TEI/text/body/div[@type="entry']/ab[@type="idnos']/idno[@type="althead' @subtype="altorder"]

Next try matching against /TEI/text/body/div[@type="entry']/head

Next try matching against /TEI/text/body/div[@type="entry']/ab[@type="idnos']/idno[@type="althead'](not[@subtype="altorder"])

For now let's not insert fuzzy matches, just exact matches and see how many are left unmatched.

@dlschwartz is the contact for this, I am just writing it up to get started

The end result should look something like this:

```
<head>Aba I</head>
            ...
            <p>Teacher of biblical interpretation, author, Cath. (540–52). Born from Zoroastrian parents, Aba converted to Christianity and studied at the <ref type="cr" target="http://gedsh.bethmardutho.org/Nisibis-School-of">School of Nisibis</ref>. He traveled to the Roman Empire and visited <ref type="cr" target="http://gedsh.bethmardutho.org/Edessa">Edessa</ref>...
```
Note that these tei:refs might occur in both tei:p or tei:ab so write the script to try and find and match them anywhere.

I have updated the sample file to show the above example.

**Comment by davidamichelson** [comment]
@wsalesky Please do normalize whitespace when comparing text nodes

**Comment by wsalesky** [comment]
How should I handle something like this:
```
<ref rend="bold">                  (see Macina, as well as M. J. Pierre, <hi rend="italic">Aphraate, le Sage persan:
                     Les exposés</hi> [SC 249; 1988], 99 n. 84).</ref>
```
Nested elements within ref.

**Comment by wsalesky** [comment]
@davidamichelson  Also, I  just noticed in the data we have:
`<idno type="uri">`
while syriaca.org uses:
`<idno type="URI">`

Can I do a find and replace for this?

**Comment by davidamichelson** [comment]
Okay, so as far as I can tell there were only 2 times when an element is inside ref. I have deleted both now and pushed to master. I also made this URI change.

**Comment by davidamichelson** [comment]
If you find other times where ref has a child element let me know please.

**Comment by wsalesky** [comment]
I don't see the uri -> URI update?

**Comment by wsalesky** [comment]
Great! Thanks.

**Comment by wsalesky** [comment]
First run, moderately successful:

https://github.com/srophe/e-gedsh/tree/issue16

Stats: 
3325 with added links
999 unmatched

I posted a full list of the unmatched here:
https://github.com/srophe/e-gedsh/blob/issue16/processing/unmatched-refs.xml

**Comment by davidamichelson** [comment]
Woo hoo! That is not moderately successful that is faboulous!

**Comment by davidamichelson** [comment]
Actually that is only 227 unique values, so actually you got us to under
300 un-matched!

**Comment by davidamichelson** [comment]
Okay and of those 227 I think Ute can actually match them very quickly so no need to run any further NER.

Don't close this issue yet thought, let me check the data further.

**Comment by davidamichelson** [comment]
@wsalesky Okay, I have checked the data and the matching looks great. I made a couple edits to the masterfile, deleted hyphens from the ref/text(), which should make even more match. Please rerun the script on the master branch data and we can close this issue. (what will happen next is that we will give you the URIs that match the strings from the unmatched file you created and we can match on those and insert them as altheads.

**Comment by davidamichelson** [comment]
One more thought. Please keep a copy of the processing/unmatched-refs.xml on the master branch please.

**Comment by wsalesky** [comment]
Okay, it is up on the master branch. Also added the updated unmatched-refs.xml to master.

**Comment by davidamichelson** [comment]
You are terrific!
