### ISSUE TITLE
Please add individual front and back matter items as list on right hand of home page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#161]
Eg. this list from here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html?lang=&sort=Front and wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html?lang=&sort=Back

Instead of showing URI's just make the list live links

Front Matter:
The Making of the Gorgias Encyclopedic Dictionary of the Syriac Heritage Author: George A. Kiraz URI: http://gedsh.bethmardutho.org/Making-GEDSH-print
Editors’ Preface Author: Sebastian P. Brock Aaron M. Butts George A. Kiraz Lucas Van RompayURI: http://gedsh.bethmardutho.org/Editors-Preface-print
List of Contributors URI: http://gedsh.bethmardutho.org/List-Contributors
Sigla and Abbreviations URI: http://gedsh.bethmardutho.org/Sigila-Abbreviations
I. General Abbreviations URI: http://gedsh.bethmardutho.org/General-Abbreviations
II. Sigla and Abbreviations for Journals, Serial Publications, and Reference Works URI: http://gedsh.bethmardutho.org/Journals-Serials-Ref-Works
III. Frequently quoted publications, referred to by the authors’s last name and short title URI: http://gedsh.bethmardutho.org/Frequently-Cited-Publications-Author-Short-Title
List of Figures URI: http://gedsh.bethmardutho.org/List-of-Figures
Back Matter:
Color Plates Author: URI: http://gedsh.bethmardutho.org/Color-Plates
Maps URI: http://gedsh.bethmardutho.org/Maps
Map I. Syriac Christianity in the Roman and Sasanian periods.URI: http://gedsh.bethmardutho.org/map/i
Map II. Syriac Christianity in the Islamic period.URI: http://gedsh.bethmardutho.org/map/ii
Map III. Syriac-Orthodox Christianity centered around Ṭur ʿAbdin.URI: http://gedsh.bethmardutho.org/map/iii
Map IV. The heartland of East-Syriac Christianity in the modern period.URI: http://gedsh.bethmardutho.org/map/iv
Map V. Main sites of Syriac Christian wall paintings in Lebanon and Syria.URI: http://gedsh.bethmardutho.org/map/iv
List of Patriarchs of the Main Syriac Churches in the Middle East Author: Samuel Burleson Lucas Van RompayURI: http://gedsh.bethmardutho.org/List-of-Patriarchs-Churches-Middle-East
I. The Church of the East and its Uniate continuations URI: http://gedsh.bethmardutho.org/Church-East-Uniate-Continuation
II. The Syriac Orthodox Church and its Uniate continuations URI: http://gedsh.bethmardutho.org/Syriac-Orthodox-Uniate-Continuations
Manuscript Index URI: http://gedsh.bethmardutho.org/Manuscript-Index

**Comment by davidamichelson** [comment]
Oops, please re-open. When you open "Front" it also opens "F" at the same
time (no big deal but a bug). When you open "Back" it opens "B" too and
thus takes you away from the list of the "Back" which is a problem.

**Comment by dlschwartz** [comment]
To clarify, this is only when you browse from the context of an article, etc.

**Comment by wsalesky** [comment]
@dlschwartz  If this looks good to you this may be closed.

**Comment by dlschwartz** [comment]
This looks great, thanks.
