### ISSUE TITLE
Add Front/Back matter to TOC on entry pages

### ISSUE THREAD

**Issue by wsalesky** [srophe/e-gedsh#162]

**Comment by dlschwartz** [comment]
@wsalesky This looks really good but there are a few issues, likely issues that I need to address in the tei. We should probably discuss a bit on Wednesday. In the front, the subsections I., II., and III., under Sigla appear in the list but the links don't work. In the back, the subsections don't show up in the list. Theses subsections are divs inside of the larger divs for Sigla and for List of Patriarchs. I think I probably need to change the encoding on these. I don't think they necessarily need to show up in the list of items in the front and back. However, when the user clicks on Sigla or on List, they ought to immediately see links that will take them directly to these three subsections. Let's discuss on Wednesday. Thanks.

**Comment by wsalesky** [comment]
It is using the `idno type="front"` and `idno type="back"` to decide what goes in those menus. I guess I can add a filter to it only gets div/@type='section'. What do you think?

**Comment by dlschwartz** [comment]
These div type="subsection" have  idno type="front" or idno type="back". 

The one for the front show up here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html?lang=&sort=Front. But the links don't work.

The ones for the back do NOT show up here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html?lang=&sort=Back

Here's an example of the back
`<div type="subsection">
                    <head rend="small-caps"><hi rend="bold">I. The Church of the East and its Uniate continuations</hi></head>
                    <ab type="idnos">
                        <idno type="URI">http://gedsh.bethmardutho.org/Church-East-Uniate-Continuation</idno>
                        <milestone unit="pages" n="481-485"/>
                         <idno type="back">9</idno>
                    </ab>`

If there were a way to have them all show up, front and back, on their respective browse pages with working links, I suppose that would be ideal. If that presents a problem, maybe these could sort on the div.

**Comment by wsalesky** [comment]
To clarify, do you want BOTH section and subsections to show up in this list, or just the section? The main browse just shows the sections.

**Comment by dlschwartz** [comment]
Currently the main browse shows them for the front but not for the back. When I select the link for the subsections on the front, I get this: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/General-Abbreviations. I think that the best case scenario would be if they showed up with working links. If that presents a problem we could do without but I would need to tweak the TEI.

**Comment by dlschwartz** [comment]
OK, I did another hard refresh (one of many in the last hour) and the subsections just disappeared from the front matter. That's weird.

**Comment by wsalesky** [comment]
Let's not worry about current behavior, instead I just need to know expected behavior. 

Essentially, include subsections in the two browse options or not. 

I'm pretty sure that bug when you clicked on a subsection link is an xquery error that I can fix.

**Comment by dlschwartz** [comment]
Sorry, I've waffled a bit on this. If we can see the subsections on the front and back pages, that would be ideal. Thank you Winona.

**Comment by wsalesky** [comment]
@dlschwartz  This has been done. If it looks good you can close this issue.

**Comment by dlschwartz** [comment]
@wsalesky This seemed good yesterday and I almost closed the issue without checking again. However, something seems to be tweaked here. The problem is the same on all of the letters and the back matter as well. All that shows up is 'Page data' and a How to cite box.

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?fq=;fq-Browse:Browse;Front;

**Comment by dlschwartz** [comment]
@wsalesky As I play around with the browse on the entries page, this problem seems to come and go. I can't figure out why though. When it goes wrong, the links to the entries also don't work. I get a 404 error: http://wwwb.library.vanderbilt.edu/Abdulmasih-II/index.html

**Comment by dlschwartz** [comment]
It looks great, thanks.

**Comment by dlschwartz** [comment]
I tried it just now. I followed that link, did a hard refresh, went to "browse entries," to "Aba," to "Front" in the left column. A first click got no response, but on a second click I ended up here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?fq=;fq-Browse:Browse;Front;. Then when I clicked on the "List of Contributors" in the left column I got the 404 error here: http://wwwb.library.vanderbilt.edu/List-Contributors/index.html
