### ISSUE TITLE
Blank search result for Gabriel Sionita?

### ISSUE THREAD

**Issue by nathangibson** [srophe/e-gedsh#163]
When I search http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?q=gabr*+sion* the 3rd result gives me http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id= 

It is a see also entry that should ultimately point to http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/al-Sahyuni-Jibrail&fq=;fq-Browse:Browse;S;

**Comment by wsalesky** [comment]
Ah, yes, it is a cross reference. Which the search was not equipped to handle. Fixed!
