### ISSUE TITLE
RDF plugin

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#165]
@wsalesky I merged your auto tagging of Syriaca persons and places. That seems find and those URIs populate the plugin. We do not see counts of resources though. This is likely just an issue with the server Dale was working on. If so, no worries. I just wanted to mention it. Also, as an fyi, I'm hoping to demo this plugin (and sing your praises!) in a talk at DH 2017 in about a month, 7 August. Please let me know if you anticipate any problems with that. Thanks Winona!

**Comment by wsalesky** [comment]
This is an RDF issue. I will check back in with Dale to see what the status of that is. I would really like to get our RDF working soon!
