### ISSUE TITLE
Search does not appear to ignore diacricits

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#166]
Thus http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?q=Beth+Abe should find:
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Beth-Abe-Monastery-of but it does not

Don't know if we have funds to fix this, just filing it for now.

**Comment by wsalesky** [comment]
Note: I believe this is the half ring issue that syriaca.org had also, I think other diacritics should be ignored as expected.

**Comment by wsalesky** [comment]
This also seems to be solved by the new Analyzer, available when we install eXist-3.6.0.

**Comment by dlschwartz** [comment]
@wsalesky Have we installed 3.6.0 yet? The initial search @davidamichelson used in creating the issue still turns up no results.

**Comment by wsalesky** [comment]
@dlschwartz we had to roll it back on the development server due to other issues. We should talk about when would be a good time to try updating dev.

**Comment by davidamichelson** [comment]
@wsalesky We are still waiting on this right for a new version of Exist?

**Comment by wsalesky** [comment]
@davidamichelson Yes, this will be solved when we upgrade eXist.

**Comment by wsalesky** [comment]
Fixed in eXist-db v4.1
