### ISSUE TITLE
Map images

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#167]
@wsalesky, we have tiff files for the e-GEDSH maps. The maps all have URIs in the TEI. I'm wondering where we can put the maps so that we can display them in e-GEDSH. Can we just put them on github? Maybe we need to host those elsewhere. Please let me know your thought/recommendations when you get a chance. Thanks!

**Comment by wsalesky** [comment]
@dlschwartz I'm not sure github is the best place for images? @davidamichelson do you have any suggestions? I would think storing them on the server in a file system would be better, and then linking to them in the TEI with a URI of some sort. Where will e-gedsh live once it is live?

**Comment by dlschwartz** [comment]
Thanks Winona. Dave and I discussed and I've been in touch with librarians here about TAMU hosting them in something new I've never heard of called Digital Asset Management Ecosystem (DAME). I'll keep you posted.

**Comment by wsalesky** [comment]
Done.
