### ISSUE TITLE
Please change the layout of the Patriarch list

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#169]
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/List-of-Patriarchs-Churches-Middle-East?fq=;fq-Browse:Browse;Back;

@dlschwartz will work on breaking these files up and renumber the footnotes so this is several seperate pages

**Comment by davidamichelson** [comment]
Do you want to change the name of this section to : List of Patriarchs of the Main Syriac Churches in the Middle East [Introduction]

**Comment by davidamichelson** [comment]
Fix the author names in the citations for the individual lists:

How to Cite This Entry
, "III. The Maronite Church" in Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition, edited by, Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay, last modified 2016-09-22-16:00, http://gedsh.bethmardutho.org/Maronite-Church-Patriarchs. 
Address : <http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Maronite-Church-Patriarchs?fq=;fq-Browse:Browse;Back;>

**Comment by wsalesky** [comment]
Who should I have as the author of the article?

**Comment by wsalesky** [comment]
I used the editors for the whole TEI if there is no article author. Let me know if that is incorrect.

**Comment by dlschwartz** [comment]
Sorry, I had managed to miss something here. I made some changes but was unable to push to Github. Problem since solved. I've restructured the TEI a bit to separate out the three lists a bit, see, http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/List-of-Patriarchs-Churches-Middle-East

**Comment by wsalesky** [comment]
Has this been resolved? It looks okay to me.
