### ISSUE TITLE
Update to schema

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#17]
As noted in https://github.com/srophe/e-gedsh/issues/5

The listBibl inside tei:div is not validating even though the guidelines say it should.

@dlschwartz This is for you ;)

**Comment by dlschwartz** [comment]
Where is this? I don't find listBibl elements in egedsh-version-0-1. Am I in the wrong place?

**Comment by dlschwartz** [comment]
Also, when I wrap the  bibl elements in a listBibl it validates just fine.

**Comment by wsalesky** [comment]
I will double check on this @dlschwartz.

**Comment by davidamichelson** [comment]
This is listBibl inside listBibl that won't validate and also @subtype on tei:idno

**Comment by wsalesky** [comment]
Thanks @davidamichelson

**Comment by davidamichelson** [comment]
@dlschwartz In the note type="abstract" there a few validation errors, don't fix those with the schema, we should just clean up the data instead.

**Comment by dlschwartz** [comment]
@davidamichelson can you remind me what we said about the hi rend="underline"? Have you fixed the problems you mentioned there? The schema currently does not allow "underline" as a value for rend. Should I update the schema to allow that?

**Comment by dlschwartz** [comment]
Sorry @davidamichelson I just checked the log and it says you have fixed those. I'll update the schema to allow hi rend="underline"

**Comment by davidamichelson** [comment]
You got it!

**Comment by davidamichelson** [comment]
Does it allow sic and corr?

**Comment by davidamichelson** [comment]
Actually there are no more rend=underline, I fixed them all by replacing

**Comment by davidamichelson** [comment]
@dlschwartz I think  you can close this right?
