### ISSUE TITLE
Get the Linked Data box up and running

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#170]
@wsalesky @dlschwartz We shoudl meet to discuss this for GEDSH this is our top priority

**Comment by davidamichelson** [comment]
One fix on the script. If the count is 0 please don't show the line:

Ex:
Resources related to Turkey

    9 related citations
    0 related subjects (should be deleted)


Resources related to Jerusalem

    related citations
    related subjects

(What is wrong here? No numbers?)

**Comment by wsalesky** [comment]
0 results stripped. 

We can meet to talk about other enhancements we may need.

**Comment by dlschwartz** [comment]
Yes, let's meet sometime soon. In the meantime, I've noticed that a change I made to the TEI for the lists of patriarchs has resulted in an odd feature in the LOD box. It seems to be grabbing the head and creating a hyperlink with it's gedsh idno even though there is no Syriaca.org idno.

**Comment by dlschwartz** [comment]
Here's the link: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Church-East-Uniate-Continuation

**Comment by wsalesky** [comment]
Thanks @dlschwartz. I fixed that.
