### ISSUE TITLE
Show TEI

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#171]
@wsalesky What do we need to do to get the show TEI working? Thanks!

I wonder if the button should be moved? It seems lonely where it is and also hard to understand it's purpose. Or should we add a print button next to it or a share on social media button.

**Comment by davidamichelson** [comment]
We like the share on social media button here at VAndy with multiple options:

**Comment by davidamichelson** [comment]
https://news.vanderbilt.edu/2017/10/26/gut-response-to-fluid-flow/

**Comment by wsalesky** [comment]
Okay, TEI is working. I will try adding a few buttons up there with the TEI.

**Comment by dlschwartz** [comment]
@davidamichelson @wsalesky I think we can close this issue. Thoughts?
