### ISSUE TITLE
webhooks

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#174]
@wsalesky After you got in touch with Dale yesterday, dev was down throughout the afternoon. During that time I committed some changes (https://github.com/srophe/e-gedsh/commit/e05c77c7fe52060c857a9df5332c0189ff88bd07) that should show up in the html but don't. Also, the first couple of times I tried a hard refresh it was really, really slow. It's faster now but still a bit slow. Thank you.

**Comment by wsalesky** [comment]
I will take a look.

**Comment by wsalesky** [comment]
I made the updates. Let me know if anything is still missing. I will also ask Dale about the slowness of the server.

**Comment by dlschwartz** [comment]
Thanks @wsalesky. I was working this morning but I only made my commits about 10 minutes ago. Unfortunately, while the commit I referenced in the original issue does appear in html now, the one I just committed still doesn't.  I've done a hard refresh several times since then. Sorry.

**Comment by wsalesky** [comment]
@dlschwartz Sorry, that was my fault, I still had the document open, so it was locked on the development server. I reran the webhook, looks good to me now.

**Comment by dlschwartz** [comment]
Great, thanks! I see it in html now too.
