### ISSUE TITLE
Map images

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#175]
Hi @wsalesky and @davidamichelson. I have managed to get the map images for eGEDSH into our repository here at Texas A&M. The system, called Oak Trust, has a IIIF API. Here are the links for the five maps. It would be great if we could start by getting our pages for these maps to display the map. The text of the print edition does not reference the maps so the only place our URIs appear is in the back element (after line 70729). Please let me know if you have any questions Winona. Thanks and have a great Thanksgiving.

Map I: http://gedsh.bethmardutho.org/map/i = http://hdl.handle.net/1969.1/165012
Map II: http://gedsh.bethmardutho.org/map/ii = http://hdl.handle.net/1969.1/165011
Map III: http://gedsh.bethmardutho.org/map/iii = http://hdl.handle.net/1969.1/165010
Map IV: http://gedsh.bethmardutho.org/map/iv = http://hdl.handle.net/1969.1/165009
Map V: http://gedsh.bethmardutho.org/map/v = http://hdl.handle.net/1969.1/165008

**Comment by wsalesky** [comment]
@dlschwartz Is there an API for accessing the images? I need to know what the IIIF server address is so I can test these. (I am following API instructions found here: http://iiif.io/api/image/2.1/#image-request-uri-syntax)

**Comment by dlschwartz** [comment]
I have an email out but still no answer. I'll let you know as soon as I do.

**Comment by wsalesky** [comment]
Reminder to self: 
http://iiif.io/api/image/2.1/#image-request-uri-syntax

**Comment by dlschwartz** [comment]
@wsalesky, I think this is what we need. Please let me know if that's not the case. Thanks!

http://labs.library.tamu.edu/fedora-iiif-service/presentation?path=Gorgias-batch-1_objects/1
http://labs.library.tamu.edu/fedora-iiif-service/presentation?path=Gorgias-batch-1_objects/2
http://labs.library.tamu.edu/fedora-iiif-service/presentation?path=Gorgias-batch-1_objects/3
http://labs.library.tamu.edu/fedora-iiif-service/presentation?path=Gorgias-batch-1_objects/4
http://labs.library.tamu.edu/fedora-iiif-service/presentation?path=Gorgias-batch-1_objects/5

**Comment by dlschwartz** [comment]
Hold that, they just told me that these are only available within the campus firewall.

**Comment by wsalesky** [comment]
Added and working. 
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Maps

**Comment by dlschwartz** [comment]
Brilliant! Thanks Winona.
