### ISSUE TITLE
image display

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#176]
@wsalesky I have finished (I hope) reconfiguring the data and adding graphic urls in the GEDSH_figs document [https://github.com/srophe/e-gedsh/blob/master/data/tei/e-GEDSH_figs.xml](url). I'm not sure how the text and links in figDesc will render. Please let me know if I need to do some additional work on this.

The main goal at the moment (and please feel free to suggest/make enhancements that seem good to you) is to give users the ability to start here: [http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/List-of-Figures](url) and then link to a page that contains the data from each corresponding div in the e-GEDSH_figs.xml file: the image, captions, and links to GEDSH articles. FYI, when articles reference images the same links also appear at the end of the article. 

A feature that would allow users to scroll through the images one by one would also be a nice touch.

Note that for 24 of the 131 images we do not anticipate being able to get permissions. I have removed the graphic element w/ url attribute entirely in those cases and simply put a note into a p element. Please let me know if I should make any changes to that structure.

Note as well that I anticipate entirely removing the Color Plates section from the back matter [http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Color-Plates?fq=;fq-Browse:Browse;Back;](url). All of that material is now in the e-GEDSH_figs.xml document. In electronic form it really doesn't make much sense to have this set off by itself. 

Please let me know if any issues or concerns arise Winona. Thanks!

**Comment by wsalesky** [comment]
@dlschwartz Thanks I hope to get to this tonight.

**Comment by wsalesky** [comment]
@dlschwartz Okay, give those links a try on http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/List-of-Figures (make sure to do a hard refresh). Or take a look at: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/fig/2

Leaving this open so I can add a way to browse all figures. Do you just want one large page with all of the figures, or do you want a next button on each figure, a list/table of contents style on the right with links to the other figures? Or some combination of these?

**Comment by wsalesky** [comment]
@dlschwartz I added paging to the figures.

**Comment by dlschwartz** [comment]
@wsalesky I think this looks great! Thanks so much for getting this together so quickly. We'll see George in Amsterdam and I am very happy to be able to show him this with images. Many thanks.

**Comment by wsalesky** [comment]
@dlschwartz Great!

**Comment by dlschwartz** [comment]
@wsalesky Are the webhooks working? I thought you had turned them off. I just posted some tweaks and they appear already. I suppose you're just that fast. One last thing. The "Color Plates" section still appears here: [http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/index.html](url). And if we could change the section titles "Figures" there to "Figures and Color Plates" that would be great. Then I think we're done with eGEDSH until the print editors weigh in. Thanks!

**Comment by wsalesky** [comment]
@dlschwartz webhooks are still off, due to the upcoming conference. I just happen to be squeezing in some working hours this morning. I will get that change to index.html up shortly.

**Comment by dlschwartz** [comment]
@wsalesky Great. No hurry on the index and feel free to close this issue after you make those changes. I think we're in great shape.

**Comment by wsalesky** [comment]
@dlschwartz Done! (Thanks for giving me something easy to check off this morning!)

**Comment by dlschwartz** [comment]
I had a feeling you'd be happy to escape RDF for a bit. Glad I could help ;)
