### ISSUE TITLE
Formatting of Manuscript Index

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#178]
@wsalesky To make the mss index a bit easier to look at, I think it would be good to indent everything not currently bolded on the page (i.e. everything except the label type="archive"). Also, it would be nice to single space all lines within each div type="subsection" but keep the double spacing between each subsection? Please feel free to suggest any additional formatting as well. Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz The way this section is currently formatted it is hard for the XSLT to differentiate the labels and the text in the subsections. I would recommend moving the labels out of the `<p>` and put the `<ref>` in the label (to keep them together). Then I can treat subsection labels one way, and subsection paragraphs another. 

So: 
```
<div type="subsection">
                    <p>
                        <label type="archive">Baghdad, Ch. of E. Archbishopric:</label>
                        <ref rend="bold" target="http://gedsh.bethmardutho.org/Baghdad">
                            <placeName ref="http://syriaca.org/place/41">Baghdad</placeName>
                        </ref>
                    </p>
                </div>
```
Should become: 
```
<div type="subsection">
       <label type="archive">Baghdad, Ch. of E. Archbishopric:
                        <ref rend="bold" target="http://gedsh.bethmardutho.org/Baghdad">
                            <placeName ref="http://syriaca.org/place/41">Baghdad</placeName>
                        </ref>
       </label>
</div>
```

**Comment by dlschwartz** [comment]
This presents a slight problem here:

```
<div type="subsection">
                    <p>
                        <label type="archive">Baghdad, Chaldean Patriarchate</label>
                    </p>
                    <p>General: 
                        <ref rend="bold" target="http://gedsh.bethmardutho.org/Baghdad">
                            <placeName ref="http://syriaca.org/place/41">Baghdad</placeName>
                        </ref>
                    </p>
                    <p>
                        <idno type="shelf">1113: </idno>
                        <ref rend="bold" target="http://gedsh.bethmardutho.org/Psalms-Syriac-Apocryphal">
                            Syriac Apocryphal Psalms
                        </ref>
                    </p>
                </div>
```

I'm not sure I know how I would create the individual lines for "General" and for "1113".

**Comment by dlschwartz** [comment]
@wsalesky I made the edit you suggest plus one more. In those instances where there is only one reference to the archive and no reference to a mss within that archive, I have added the text "General:" within a p element. That means that all of these divs now have a consistent format: div type=subsection with a label type="archive" followed by one or more p elements with a combination of text and refs.

We'll want the label elements in bold and left adjusted with the p elements not bolded and indented. Also, we'll want single spacing within each div and double spacing between divs. 

I hope this is nice and easy. Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz Thanks! I will take a look.

**Comment by wsalesky** [comment]
@dlschwartz How does this look? http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Manuscript-Index

**Comment by dlschwartz** [comment]
The basics are good. We are getting spaces between headword links and punctuation. See Add. 12,150. Also, I made a couple of changes to the TEI that aren't appearing. Look at the first items in the mss list. They should all have "General:" appearing before the linked headword. Did my changes from Friday get pushed? I did a hard refresh but I don't see those changes. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz no your new changes did not get pushed, I have had webhooks turned off because of presentations, I think I can turn them back on this week. I will push your new changes manually.

**Comment by dlschwartz** [comment]
Great, thanks. Also, I don't see single spacing within divs and double spacing between divs. I think that would help set off each archive.

**Comment by wsalesky** [comment]
Okay, I fixed the spacing also. You may need to do a hard refresh to see it.

**Comment by dlschwartz** [comment]
I'm still seeing the old stuff (html and tei). I did a hard refresh. I tried closing and re-opening my browser. I even tried the nuclear option...I looked in Explorer!!! They all show the old stuff.

**Comment by wsalesky** [comment]
This is what it looks like:
<img width="606" alt="screen shot 2018-03-26 at 2 11 08 pm" src="https://user-images.githubusercontent.com/1168206/37924332-8feebfd4-30ff-11e8-8447-4ca67884ebcf.png">

**Comment by dlschwartz** [comment]
Yes, this is what I see too. But this doesn't include the changes made in this and subsequent commits: 04a8d66aa1f3ab7bb327ce87a21ff4ea61f0fecb. Did these not get pushed to dev yet?

**Comment by wsalesky** [comment]
@dlschwartz just pushed new version to dev. how does it look?

**Comment by dlschwartz** [comment]
Yes, that's it! Thanks Winona. I'll go ahead and close this.
