### ISSUE TITLE
Adjust body of the articles

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#180]
@wsalesky George would like the body of the articles to have the margins adjusted. I'm not sure how this works especially when changing the screen size or using a phone. Let me know if you foresee problems. Otherwise, let's go ahead with this. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz adjusted how?

**Comment by wsalesky** [comment]
Okay, done. You can test it out next week.
