### ISSUE TITLE
indent front and back subsections in browse

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#184]
@wsalesky In the browse for the front and back (http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html?lang=&sort=Back) we see the div type="section" and the div type="subsection" all left adjusted. It would be great to indent div type="subsection" lines to highlight the structure of the material a bit better. Thanks.

**Comment by wsalesky** [comment]
Fixed. Will push early next week in order to keep dev server stable.
