### ISSUE TITLE
Bibliography formatting

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#185]
@davidamichelson Can you give me your thoughts on some formatting here? See the following three entries: 
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Malankara-Syriac-Orthodox-Church
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Man-of-God-of-Edessa
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Mani
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Moberg-Axel

We've got kind of a mess of labels, absence of labels, and different types of notes preceding bibliographies. This economy allowed George to save a lot of lines of text but it seems a bit awkward here. I'm trying to limit the addition of work but this one might need to be addressed. Let me know your thoughts.

**Comment by dlschwartz** [comment]
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Christian-Palestinian-Aramaic
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Fiey-Jean-Maurice
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Ishaq-of-Nineveh
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Macarian-Homilies
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Liturgy
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Malankara-Syriac-Orthodox-Church [change first bibl to note or p]
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Martyrs-and-persecutions [change bibls to note or p]
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Mushe-bar-Kipho [sort out mixture of text and bibl]

**Comment by dlschwartz** [comment]
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Theano
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Yaqub-of-Serugh
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Gabriel-Monastery-of-Mor [change first bibl to note or p?]
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Yahbalaha-III [change bibl to note or p]

**Comment by dlschwartz** [comment]
Four main issues:
1) notes preceding the first bibliographic entry
2) formatting of head elements
3) formatting of multiple nested head elements
4) absence of any head from many bibliographies (might not need to concern us)

**Comment by dlschwartz** [comment]
@wsalesky I've made some changes to the TEI to address problems I've worked through in the above comments. I would like to tweak the display of bibliography in the html a bit. Things can get confusing with some complicated head elements (i.e. http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Christian-Palestinian-Aramaic). We might need some additional formatting but let's start here. Thanks.

1) Left adjust all head, bibl, and p elements within div type="bibl"
2) Single space bibls and single space between bibl elements 
3) Double space between listBibl elements

**Comment by dlschwartz** [comment]
@wsalesky Actually, I've checked and I think it would be good to left adjust all head and bibl elements in listBibl throughout e-GEDSH. By the way, not all head and p elements in div type="bibl" (see 1 in the comment above) are inside of a listBibl element.

**Comment by dlschwartz** [comment]
@wsalesky I'm so sorry, I forgot to mention one caveat on the bibl elements. We would like them left adjusted for the first line but we do want them to have the hanging indent. Sorry I forgot this. Thanks.

**Comment by dlschwartz** [comment]
@wsalesky FYI, a change to the bibls just appeared for me. We have a first line indent where I think we want a hanging indent. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz Done! (You will need to do a hard refresh to see the change)

**Comment by dlschwartz** [comment]
Looks great, thanks!
