### ISSUE TITLE
small caps

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#186]
There is an instance of small caps in a bibliographic item that is not displaying in html.
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Church-East-Uniate-Continuation

**Comment by wsalesky** [comment]
@dlschwartz Do you mean in the citation? 
<img width="698" alt="screen shot 2018-03-26 at 10 39 32 am" src="https://user-images.githubusercontent.com/1168206/37913076-02c41e50-30e2-11e8-978d-2cfed11eecbf.png">

**Comment by dlschwartz** [comment]
No, sorry this wasn't clearer. It's in the bibliography section. Look at the TEI (http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Church-East-Uniate-Continuation/tei) and search for "small-caps". That's not displaying correctly.

**Comment by wsalesky** [comment]
How does it look now?

**Comment by wsalesky** [comment]
@dlschwartz I think this issue is superseded by this one: https://github.com/srophe/e-gedsh/issues/193
