### ISSUE TITLE
numbering of some bibl elements

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#187]
@wsalesky In the bibliographies that include a head element the first bibl element has no attribute. In bibliographies that have no head the first bibl (and only the first bibl) includes an "n" attribute with a value of 1. Is the XSLT doing anything with this. I would like to delete it if we aren't using it but don't mind keeping it if we are. Thanks.

**Comment by dlschwartz** [comment]
`<div type="bibl">
                    <listBibl>
                        <bibl n="1">Munūfar Barṣūm, <title rend="italic">Aḍwāʾ</title>, 35–8,
                            63–4.</bibl>
                    </listBibl>
                </div>`

but 

`<listBibl>
                            <head>Primary Sources</head>
                            <bibl>G.  Diettrich, <title rend="italic">Eine jakobitische Einleitung
                                    in den Psalter</title> (Beihefte zur <abbr>ZAW</abbr> 5; 1901).</bibl>`

**Comment by wsalesky** [comment]
@dlschwartz We are not using that attribute for processing or display, I think you can safely remove it.

**Comment by dlschwartz** [comment]
Great, thanks. I'll remove that. This helps me sort out some issues with bibliography headings. More on that soon.
