### ISSUE TITLE
mss index formatting

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#188]
@davidamichelson Just interested in some quick input on an idea. The mss index (http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Manuscript-Index) is improving but is still a bit hard to look at. What do you think about 

Ḥenanishoʿ I | Ishoʿbokht of Rev Ardashir | Shemʿon of Rev Ardashir | Synodicon Orientale

instead of the current

Ḥenanishoʿ I; Ishoʿbokht of Rev Ardashir; Shemʿon of Rev Ardashir; Synodicon Orientale

**Comment by davidamichelson** [comment]
Yes use pipe character

**Comment by dlschwartz** [comment]
I think this is good and so I'll close the issue. You should let me know if you think otherwise @davidamichelson
