### ISSUE TITLE
Changes to Linked Data Box

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#192]
Please make the following changes.

1. When an article has no linked data for its main subject (for example http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Christian-Palestinian-Aramaic) then please have a test for the box. If related resources = 0 or there is no idno type="subject" which has a Syriaca.org URI for the article, then please supress the line "Resources related to "Title" altogether.

2. Please revise the labels in this way in general:

Current:

Resources related to Antioch

181 related subjects 

> Note: Something is wrong with this count. It should be breaking this down into related subjects and citations like with the results in the expanded view.

Resources related to 21 other subjects. Show...

Revised:

Resources related to Antioch

X related subjects

Y related citations 

Resources related to 21 other topics in this article. Show...

> Note: This last line can wrap if needed.

**Comment by wsalesky** [comment]
Fixed the labels. We will have to investigate the SPARQL query to fix that count for Antioch, I maybe counting the citations incorrectly. 

Current SPARQL query: 

```
       prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
        prefix owl: <http://www.w3.org/2002/07/owl#>
        prefix skos: <http://www.w3.org/2004/02/skos/core#>
        prefix xsd: <http://www.w3.org/2001/XMLSchema#>
        prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
        prefix lawd: <http://lawd.info/ontology/>
        prefix dcterms: <http://purl.org/dc/terms/>
        prefix foaf: <http://xmlns.com/foaf/0.1/>
        prefix dc: <http://purl.org/dc/terms/>      
                                
        SELECT (COUNT(*) AS ?count)
        WHERE {
          <http://syriaca.org/place/10> dcterms:relation ?o;
        }
```

**Comment by davidamichelson** [comment]
Revised Script for the Linked Data Counts:

Related Subjects = dcterms:relation in the RDF for the given uri (ex. place/78)

Citations =  dcterms:source + skos:closeMatch

**Comment by wsalesky** [comment]
Counts have been amended. Next up, add Javascript loading.

**Comment by davidamichelson** [comment]
Great work!

**Comment by wsalesky** [comment]
Fixed.
