### ISSUE TITLE
How to Cite

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#193]
@wsalesky Here's what we would like: 

How to Cite this Entry
Footnote Citation:
H. Takahashi, "Antioch" in Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition, edited by, Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay, http://gedsh.bethmardutho.org/Antioch.
See more information about this entry… [with a link that expands to show below]

[after expansion]

Bibliography Entry Citation:
H. Takahashi, "Antioch" in Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition, edited by, Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay. Digital edition prepared by Ute S. Posssekel and Daniel L. Schwartz, http://gedsh.bethmardutho.org/Antioch.

A TEI-XML record with complete metadata is available here [with link to: http://gedsh.bethmardutho.org/Antioch/tei.

Thanks Winona. Let me know if you have any questions.

**Comment by dlschwartz** [comment]
@wsalesky Let's also run a test for whether or not a byline element appears for each section. If there is no byline element then the entry should simply skip the author name and begin with the title [tei head element]. The rest should be the same.

**Comment by wsalesky** [comment]
@dlschwartz I add these changes, if it looks good to you, you can close it.

**Comment by dlschwartz** [comment]
@wsalesky I think this is looking pretty good.  We do have some minor issues still. In the the front and back matter sections (but not in the articles) the titles appear in bold and have a space between the parentheses and the title. See http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/List-of-Patriarchs-Churches-Middle-East. 

Also, I'm not sure why Dave and I came up with the language we did for the expansion link. I prefer exactly what we have on Syriaca.org pages which is "Show full citation information..." Let's go with that instead.

With those two caveats, this looks great and, most importantly, I think it will make George and the editors of the print edition happy. Thanks.

**Comment by dlschwartz** [comment]
Just in case it's not clear, we should remove the spaces and put the titles in regular font as in the articles. Thanks.

**Comment by wsalesky** [comment]
The spaces are in the XML. Because there are a lot of places where white space is important I can not programmatically remove this, without causing havoc, so we will have to edit the XML directly to get rid of the spaces.

**Comment by dlschwartz** [comment]
I should have checked that first. I'll remove those. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz should the titles not render in small caps? Or just small caps, not bold? (Both bold and small caps are indicated in the XML)

**Comment by dlschwartz** [comment]
Two things here. Currently the tei describes what's in the print edition, bold and small caps. This is what appears in the heading on each page and I think this looks fine as is. In the citation section, however, it would be nice to strip this out. Can we do that?

**Comment by dlschwartz** [comment]
Yes, the title in the citation section should be the same font as the other text.

**Comment by dlschwartz** [comment]
@wsalesky If the last commit I made doesn't do the trick, I have another idea. Instead of 

`<head rend="small-caps"><hi rend="bold">Manuscript Index</hi></head>`

We could try
`<head rend="small-caps bold">Manuscript Index</head>`

Let me know if I should try this.

**Comment by wsalesky** [comment]
@dlschwartz that last commit removed the space. I still need to ignore the rend attribute.

**Comment by dlschwartz** [comment]
@wsalesky One more thing. Can we get smart quotes instead of straight quotes on these?

**Comment by wsalesky** [comment]
@dlschwartz I think I caught them all. If it looks good, you may close the issue.

**Comment by dlschwartz** [comment]
@davidamichelson Do you think it would be better to use the label "Full Bibliographic Citation" to suggest that what appears above is something else without specifically noting that it is a footnote citation.

**Comment by davidamichelson** [comment]
Three comments, listing them all here even though the first two are just typo issues.

First, actually the footnote and bibliography styles are now identical. I think this is a mistake we did not catch. Dan?

Second, Ute Possekel is misspelled with three "sss". I think this is a mistake we did not catch. Dan?

Third, on the issue at hand. I think the way it currently is, is confusing since only the bibliographic citation is labeled. I think this method is confusing on Syriaca.org in general. Instead, could we have it be that when you click full citation information it lists both footnote and bibliography styles with full labels and today's date auto generated as access date?

**How to Cite this Entry:**

> H. Takahashi, “Antioch” in Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition, edited by, Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay, http://gedsh.bethmardutho.org/Antioch.              Show full citation information...

after expansion:

**How to Cite this Entry:**

> H. Takahashi, “Antioch” in Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition, edited by, Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay, http://gedsh.bethmardutho.org/Antioch.    
> 
> **Footnote Style Citation:**
> H. Takahashi, “Antioch” in Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition, edited by, Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay, accessed October 31, 2018, http://gedsh.bethmardutho.org/Antioch.
> 
> **Bibliography Entry Style Citation:**
> Takahashi, H. “Antioch.” In Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition. Edited by, Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay. Digital edition prepared by Ute S. Possekel and Daniel L. Schwartz. Accessed October 31, 2017. http://gedsh.bethmardutho.org/Antioch.
> 
> A TEI-XML record with complete metadata is available here http://gedsh.bethmardutho.org/Antioch/tei.
>

**Comment by dlschwartz** [comment]
@davidamichelson I'm fine with this. Thanks for catching the typos I missed (or even created). They aren't identical actually. The difference between the two is that the "footnote" citation style doesn't include a reference to those responsible for the digital edition. I'm happy with what you've suggested here Dave. @wsalesky please let us know if you need anything more to implement this.

**Comment by davidamichelson** [comment]
Thanks, just to clarify the footnote style should use commas and the bibliography style should use periods is what I am trying to note.

**Comment by wsalesky** [comment]
@dlschwartz @davidamichelson Updated and ready for review.

**Comment by davidamichelson** [comment]
Looks good with one exception. I don't think the author's last name is parsing, "H. Takahashi" it should be reversed for the Bibliography entry as "Takahashi, H.". Maybe the TEI is not formatted to allow this?

**Comment by dlschwartz** [comment]
@davidamichelson We have the entire name appearing in a byline element. We would have to add name elements to the tei.

**Comment by davidamichelson** [comment]
One more request, let's change "Show full citation information..." to "More information..."

**Comment by dlschwartz** [comment]
I think we also have a slight punctuation issue.  The footnote option has a period after the name while the bibliography has a comma after the name. I think that should be switched.

**Comment by davidamichelson** [comment]
Hmm, could we fix the names easily en mass? Might be easy to do by a script

**Comment by davidamichelson** [comment]
I am not comfortable with having the citation be misformed :)

**Comment by wsalesky** [comment]
@davidamichelson I don't think it is regular enough to script the  change. Sometimes there is more then one author, some authors have first and middle initials, some first name middle initial, some first initial, some have Jr. or last names with a space. etc. I could try a script, but there would have to be some heavy review to catch the odd cases.

**Comment by dlschwartz** [comment]
@wsalesky @davidamichelson I'm close to finishing adding forename and surname elements to the persName elements in tei. Fortunately, a few authors did most of the entries and a quick find and replace got me a lot of the way there. I'll let you know when I'm done.

**Comment by dlschwartz** [comment]
@wsalesky I've added forename, surname, and genName elements (for things like "Jr."). I'm not quite done yet because I'm having trouble with Oxygen. There is enough in there to make changes and test things though. There are multiple authors in some byline elements and we would only want the first author to appear in bibliography citation as surname, genName, forename. Can we order the name parts like that only in the first persName element in a byline element? Thanks.

**Comment by dlschwartz** [comment]
@wsalesky The last commit has all names in byline elements separated out. Each individual person is wrapped in a persName element as well as forename and surname for name parts. In a few instances there are also genName elements for things like "Jr.". These should be all the elements appearing in the byline element.

**Comment by wsalesky** [comment]
Thanks! I will take a look.

**Comment by wsalesky** [comment]
Thanks, @dlschwartz changes are up and citations look good to me. Let me know if you spot any issues.

**Comment by davidamichelson** [comment]
Almost done, one item was forgotten. Before the expansion please change the
"Show full citation..." to "Show more information..."

Also on my screen the line: "A TEI-XML record with complete metadata is
available here http://gedsh.bethmardutho.org/Antioch/tei." is justified on
both sides resulting in odd stretched whitespace.

Almost there!!!!

**Comment by dlschwartz** [comment]
@wsalesky And I think we need a comma inside the parentheses for the title of the article in the footnote format.

**Comment by davidamichelson** [comment]
Please change: "A TEI-XML record with complete metadata is available here http://gedsh.bethmardutho.org/Bible-New-Testament-manuscripts/tei." 
to

"A TEI-XML record with complete metadata is available as http://gedsh.bethmardutho.org/Bible-New-Testament-manuscripts/tei."

ie change "here" to "as"

**Comment by dlschwartz** [comment]
@wsalesky It looks great to me. @davidamichelson?

**Comment by dlschwartz** [comment]
@wsalesky I just noticed one small problem. In the dates, there is a space between the month and the comma.  It would be good to remove this.

**Comment by wsalesky** [comment]
@dlschwartz Can you post a screen shot? I'm not seeing it.

**Comment by dlschwartz** [comment]
![howtocite](https://user-images.githubusercontent.com/4984270/38623828-401da276-3d6c-11e8-8dc0-15683856982f.JPG)

@wsalesky Here's the screen shot. I missed it earlier but noticed it when I looked at one example where the line ended with "April" and the next line started with a ",". It appears throughout the citation sections for me.

**Comment by wsalesky** [comment]
Thanks, fixed.
