### ISSUE TITLE
Footnote in Patriarch lists

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#196]
@wsalesky There are a couple of issues with footnotes in patriarch lists. 

1. See http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Church-East-Uniate-Continuation. Some note elements are in the head under div type="subSubsection". The xPath for one of them is /TEI/text[1]/back[1]/div[3]/div[1]/head[1]/note[1]. These notes appear at the end of each div type="subSubsection". But, they also appear a second time at the end of the page. Currently, when you click on one of these note number links, it takes you to the note that appears at the end of the div.

2. On the same page, there is one note element (1) that appears inside of a table. The xPath is /TEI/text[1]/back[1]/div[3]/table[1]/row[90]/cell[2]/note[1]. This does not appear at the end of its div but does appear at the end of the page. Clicking on this note number link takes you to the note at the bottom of the page.

Perhaps it is easiest simply to remove the notes from the end of the divs and have them all appear only at the bottom of the page. Links in the note numbers would have to direct users there. People will have to use their back button to return to the text after clicking on the footnote link but that should be fine.

This is a little complicated, please let me know if you have any questions. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz We can use the Corpus style footnote system, where there is a popup when you click on a footnote, and then all the footnotes are listed at the bottom of the page as well.

**Comment by wsalesky** [comment]
@dlschwartz Okay, tell me what you think of the new version.

**Comment by dlschwartz** [comment]
@wsalesky This seems to be working well in the first of the Patriarchs sections: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Church-East-Uniate-Continuation. You've gotten rid of the duplicate footnotes which is great and the pop ups seem to work well. In other sections, the pop ups appear on top of the regular text. Can we force those into the margin? 

See notes 1 and 7 here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Syriac-Orthodox-Uniate-Continuations

See note 2 here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Maronite-Church-Patriarchs

See as well the notes here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Making-GEDSH-print

**Comment by dlschwartz** [comment]
And we have syriaca.org URIs in the patriarchs pages but the LOD box doesn't seem to be showing up. Once we get that back in, will this cause problems for where the pop ups appear?

**Comment by dlschwartz** [comment]
@wsalesky The footnote pop ups are now appearing in a box. I think this looks good and solves the problem of appearing on top of the text.

**Comment by wsalesky** [comment]
@dlschwartz Great, I think I misunderstood what the problem was before. I suspect your CSS settings just reset so the appearance is correct now.  Can I close this?
