### ISSUE TITLE
Initial Transformations to Data

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#2]
@wsalesky 

The current best version of the data is: https://github.com/srophe/e-gedsh/blob/master/egedsh-pre-tei-version-2.xml

This is only part of the data (about 1/6 of the whole, it is all entries for letter A), so we will have to run this clean up again so please save any scripts.

The current desiderata are:

Issue One: Where there is a /TEI/text/body/div/div[@type="bibliography"] it may have tei:label elements breaking it up into sections. It would be good to use these labels to create tei:div(s) where the tei:div/@type is the textnode of the tei:label

Thus 
```
<div type="bibliography">
     <label>Primary Sources</label>
```
becomes
```
<div type="bibliography">
     <div type="Primary-Sources"
     <label>Primary Sources</label>
...</div>
```
The closing div would come either before the next label or the end of the div[@type="bibliography"] 

Issue Two:

Each entry has approximately the following tree

div @type="entry"
- head
- div @type="infobox"/tei:ab
- div @type="body"
- div @type="bibliography"
- byline

BUT the part of the tree that is div @type="infobox" is not very clean or consistent and is not in all entries.

Is there a way to check that if there are any nodes between  /head and  div @type="body" they are properly wrapped?

**Comment by davidamichelson** [comment]
One note, in the mean time I found the XML of the all entries, so I will try to clean that up tomorrow same way that I did this batch. So perhaps wait until then.

**Comment by wsalesky** [comment]
Let me know when this is ready @davidamichelson

**Comment by davidamichelson** [comment]
Opening new shorter issue
