### ISSUE TITLE
Linked data box not appearing

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#200]
@wsalesky I was checking this article http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Christian-Palestinian-Aramaic for bibliography formatting and noticed that there was no LOD box. I checked and there are six syriaca.org URIs in the body. I'm not sure how common this might be. Thanks.

**Comment by wsalesky** [comment]
Fixed
