### ISSUE TITLE
SPARQL query produces duplicates, sometimes

### ISSUE THREAD

**Issue by wsalesky** [srophe/e-gedsh#201]
@davidamichelson @dlschwartz The e-gedsh query occasionally gives me duplicate ids. I will need some help debugging the SPARQL. Know any experts that might be able to help? Or should I resort to asking on StackOverflow?

**Comment by dlschwartz** [comment]
@davidamichelson Do you know anyone? I don't think I do, sorry.

**Comment by wsalesky** [comment]
This has been solved.
