### ISSUE TITLE
URI search

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#205]
@wsalesky What exactly does the URI search look at? George pointed out that we get results from just searching for a name "aba": http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?q=&placeName=&persName=&bibl=&uri=aba. 

Should that happen?

He also asked whether searching by a URI should return only one entry. That is of course not the case because all of the cross references in e-GEDSH use the same gedsh URI for that reference and a syriaca.org URI can appear in many contexts. 

Do you have any thoughts on how we can clarify this search for less technically savvy users? @davidamichelson?

**Comment by wsalesky** [comment]
@dlschwartz Honestly I don't remember what it was supposed to search, if we can clarify I can adjust the code.

**Comment by wsalesky** [comment]
@dlschwartz @davidamichelson I have updated the regex on the URI search so that it is more restrictive, it will only return exact matches for `tei:idno[@type='URI']`, `@ref`, and `@target`

**Comment by dlschwartz** [comment]
The updated regex for URI search looks good to me. We would like to follow the model on the Gazetteer: 
![urisearch](https://user-images.githubusercontent.com/4984270/39140187-77663866-46e9-11e8-87e5-d187cb7b3c42.JPG)

In GEDSH the implementation would have the label "URI:"
The asterisk below should read "Enter GEDSH or Syriaca URI, ex. http://gedsh.bethmardutho.org/Aba, or http://syriaca.org/person/13"

@davidamichelson Please write and post to this issue a blurb to appear in a popup explaining what a URI is and how to use this search.

**Comment by wsalesky** [comment]
Added hint.

**Comment by dlschwartz** [comment]
I like this. @davidamichelson let us know if you want to add anything to the popup.

**Comment by davidamichelson** [comment]
Looks good so far! Can we change the pop up to this please:

"Searches the entire XML data, and returns entries which reference specific URIS (GEDSH, Syriaca.org, etc)."

**Comment by wsalesky** [comment]
Done.

**Comment by davidamichelson** [comment]
My mistake, in both the pop up and the hint, please change "GESDH" to "e-GEDSH" also please change the pop up to: "Searches the entire XML data and returns the entries that reference the specified URI(s)." which is shorter.

**Comment by wsalesky** [comment]
@davidamichelson Updated.

**Comment by davidamichelson** [comment]
Great!

**Comment by dlschwartz** [comment]
@wsalesky I can't see the popup. I hover over it and I get the popup flashing like a strobe light. It's so fast I can't read it. I'm in Chrome on a PC.

**Comment by davidamichelson** [comment]
It works for me on firefox for mac

**Comment by dlschwartz** [comment]
I hate to say it but I actually opened IE and it works fine there.

**Comment by wsalesky** [comment]
@dlschwartz Does this happen even with a hard refresh?

**Comment by dlschwartz** [comment]
@wsalesky A hard refresh didn't do the trick but it's working now. I've turned my computer on and off, maybe that explains it. Does this close the issue? I think so.

**Comment by wsalesky** [comment]
Yes!
