### ISSUE TITLE
Landing page: editors

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#206]
@wsalesky George would like the landing page to look like what you've done for Hugoye: http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/index.html. We're nailing down the text for the section below the banner and I'll put that into another issue once it's ready. For the editors, he would like the same format as Hugoye with the following text:

General Editor
     George Anton Kiraz, _Beth Mardutho: The Syriac Institute_
Print Edition Editors
     Sebastian P. Brock, _University of Oxford_
     Aaron M. Butts, _Catholic University of America_
     George Anton Kiraz, _Beth Mardutho: The Syriac Institute_
     Lucas Van Rompay, _Duke University_
Digital Edition Editor:
     Ute Possekel, _Harvard University_
Technical Editors, Electronic Edition:
     David A. Michelson, _Vanderbilt University_
     Daniel L. Schwartz, _Texas A&M University_
Software Design and Implementation [or whatever title you prefer Winona]:
     Winona Salesky

**Comment by dlschwartz** [comment]
Just to be clear, the names should be indented as they are on the Hugoye page.

**Comment by wsalesky** [comment]
Added

**Comment by dlschwartz** [comment]
@wsalesky Sorry, I was hurrying on Friday when I wrote this up and just copied what George put in. We shouldn't have an editor of the "Digital Edition" and technical editors of the "Electronic Edition". Can we change Technical Editors, Electronic Edition to "Technical Editors, Digital Edition". Thanks.

**Comment by wsalesky** [comment]
@dlschwartz better?

**Comment by dlschwartz** [comment]
Yes, that's great. Thanks.
