### ISSUE TITLE
Landing page: Left side

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#207]
Side List
Replace “Author:” with “by” in the front and back matter sections

Add italics to have: The Making of the _Gorgias Encyclopedic Dictionary of the Syriac Heritage_

**Comment by dlschwartz** [comment]
https://github.com/srophe/e-gedsh/commit/00613c7d97dd17b136c5992d263b4adedc532f87 This commit adds italics to the title which should italicize on the landing page but also here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Making-GEDSH-print. I think both are appropriate.

**Comment by wsalesky** [comment]
@dlschwartz Do you mean it should italicize the header in the image? We turned off the rendering of italics and bold in this part of the display, so there may be some knock-on effects of adding the italics back in here. 
<img width="645" alt="screen shot 2018-04-23 at 9 25 41 am" src="https://user-images.githubusercontent.com/1168206/39129417-72e6a408-46d8-11e8-8f64-2f28c8b89e93.png">

**Comment by dlschwartz** [comment]
@wsalesky I currently see the italics in the front matter section here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/index.html. That was George's request. I thought that perhaps adding it to TEI as I did would also make it appear in the display of the header here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Making-GEDSH-print.  I don't currently see that displayed. If there's a chance it will cause a problem elsewhere, I think we should just leave things as they are. Thanks for hitting all of these issue!

**Comment by wsalesky** [comment]
@dlschwartz I think this can be closed as well.

**Comment by dlschwartz** [comment]
yes
