### ISSUE TITLE
Links to articles from contributors page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#208]
@wsalesky George asks: Is it possible to add a hyper link under each name and clicking on it takes you to a page that lists the articles by that author with links to the article page?

There is nothing in the TEI at the moment that would facilitate this. 

We could add a search by author section to the advanced search page. I could add a ref element to the names in the list of contributors like I did for the cross reference heads that suggested spelling variations. This would give us a link on the names that would search by author and return results.

I'm sure there are other ways to do this. What are your thoughts Winona?

**Comment by wsalesky** [comment]
@dlschwartz Yes this is possible. I can easily add an author search, no additional tagging needed.

**Comment by dlschwartz** [comment]
@wsalesky Once we have an author search built, I was thinking that I could add links to names here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/List-Contributors. For example, `<ref type="authorLookup">Joseph P. Amar</ref>` that we could treat like we do the cross references in browse:
![crossreference](https://user-images.githubusercontent.com/4984270/39132538-b07996d2-46d7-11e8-8f00-6b3496dcbc3a.JPG)
`<ab type="crossreference">see <ref type="lookup">Iwannis</ref>, <ref type="lookup">Yoḥannan</ref> (<abbr>E. Syr.</abbr>), and
                        <ref type="lookup">Yuḥanon</ref> (<abbr>W. Syr.</abbr>)
                </ab>`

How does that sound?

**Comment by wsalesky** [comment]
Author search is up: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?author=Kiraz

If you want to add authorLookup to the xml I will update the html output

**Comment by wsalesky** [comment]
@dlschwartz The code is in place, let me know when the XML is updated and we will test it.

**Comment by dlschwartz** [comment]
@wsalesky All persName values in the contributor list now match the persName values in the bylines. Also, all persName elements in the contributor list have been wrapped in ref type="authorLookup". Let me know if you need anything else.

**Comment by wsalesky** [comment]
@dlschwartz See: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/List-Contributors
If that works as expected you can close this.

**Comment by dlschwartz** [comment]
@wsalesky This looks great! I do have one question about the Contributor search. The results show instances of the search terms from the body of the text. See for example http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?q=&author=walker&placeName=&persName=&bibl=&uri=. Here the appearance of "Walker" is highlighted. Since we are only searching the author field and the person searching expects to get articles written by a person regardless of whether or not that person's name appears in the body, can we simply suppress the "keyword in context" feature on the search results. It's not a big deal. If is will cause problems for search, that's fine, we should leave it. The results for URI search don't show this and it just looks nice and clean: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?q=&author=&placeName=&persName=&bibl=&uri=http%3A%2F%2Fsyriaca.org%2Fperson%2F13. Thanks Winona! Things are looking great.

**Comment by wsalesky** [comment]
@dlschwartz I don't think I can turn the KWIC of just for author searches, without it effecting other types of searches.

**Comment by dlschwartz** [comment]
@wsalesky No worries. I thought that might be the case. This was a very minor concern. I'm happy to keep things as is and close the issue. Thanks.
