### ISSUE TITLE
Whitespace got normalized in commit https://github.com/srophe/e-gedsh/commit/968919490e744d876c85a1645de9e68b21a3e927

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#21]
It looks like this happened in this commit: https://github.com/srophe/e-gedsh/commit/968919490e744d876c85a1645de9e68b21a3e927

Notice that whitespace before and after ```<ref>, <title>, and <hi>``` among others got deleted but we need that whitespace to remain. Sorry if our earlier conversation about normalization raised this confusion!

p.s. If you have to roll back the data that is fine just let me know and I will also make my changes again that lead to this commit: https://github.com/srophe/e-gedsh/commit/6633b43da12338c81a93c0ed0874aa9c02d2a84a

**Comment by wsalesky** [comment]
@davidamichelson  here is an updated version (on a branch). It looks okay to me, can you double check. 

https://github.com/srophe/e-gedsh/tree/issue21

**Comment by davidamichelson** [comment]
@wsalesky Yes, it looks good. Thank you! Please run any remaining scripts and push to master.

**Comment by wsalesky** [comment]
Okay
