### ISSUE TITLE
Title underline in Patriarch lists

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#210]
@wsalesky See the first bibliographic item here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Syriac-Orthodox-Uniate-Continuations. The Syriac title is wrapped in `<title xml:lang="syr">`. Can we remove the underline and just have this in a regular font.

**Comment by wsalesky** [comment]
Fixed.
