### ISSUE TITLE
Left side browse indent

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#212]
@wsalesky See http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Aba?fq=;fq-Browse:Browse;A;. George asks: When clicking on a letter of the alphabet, is it possible to show the subentries indented so that one realizes that one is in a tree structure?

I think we could do a little bit but wouldn't want to do too much indenting.

**Comment by wsalesky** [comment]
Fixed
