### ISSUE TITLE
Logos on the landing page

### ISSUE THREAD

**Issue by wsalesky** [srophe/e-gedsh#214]
@davidamichelson Does Vanderbilt need two mentions here (Vanderbilt and Heard Library?)

**Comment by wsalesky** [comment]
@dlschwartz I think this can be closed?

**Comment by dlschwartz** [comment]
Agreed. Thanks

**Comment by wsalesky** [comment]
added

**Comment by davidamichelson** [comment]
Sorry a couple of quick changes, can we please swap the place of the NEH and Srophe logos in the ordering? Also the Vanderbilt logo with the V looks very low resolution, do you need a different file?

**Comment by davidamichelson** [comment]
@dlschwartz Please weigh in if you don't mind, but seems NEH should be by Balzan and Srophe can be at the end unless you think it should stay where it is.

**Comment by dlschwartz** [comment]
@davidamichelson Well, George said that he wanted BM, Gorgias, Srophe and then all the rest. I don't have strong feelings on this. Srophe is becoming a publishing platform so I think it's acceptable to put it with the other publishing platforms. I would go from these three to as is to Balzan, NEH, etc. That's my two cents. Feel free to give Winona the final word.

**Comment by davidamichelson** [comment]
Okay let’s keep stooge as is but bump NEH up next to Balzan

**Comment by davidamichelson** [comment]
Lol Srophé auto corrects to stooge on iPhone

On Wed, Apr 25, 2018 at 3:52 PM David Michelson <david.a.michelson@gmail.com>
wrote

**Comment by dlschwartz** [comment]
I was wondering about that

**Comment by wsalesky** [comment]
@davidamichelson Yes if you can get a different version that would be great.

**Comment by wsalesky** [comment]
@davidamichelson Just a reminder, if you can get a better resolution of the Vanderbilt logo that would be great.

**Comment by davidamichelson** [comment]
@wsalesky also just sent new VU logo options, please pick the best one and update across all projects.

**Comment by dlschwartz** [comment]
@davidamichelson @wsalesky I think this can be closed? Is that right?

**Comment by wsalesky** [comment]
Yes.

**Comment by wsalesky** [comment]
@davidamichelson I think this can be closed?

**Comment by davidamichelson** [comment]
Yes thanks!
