### ISSUE TITLE
Landing page blurb

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#215]
@wsalesky Here is the text that we just hammered out: 

e-GEDSH is an electronic version of the 2011 edition of the Gorgias Encyclopedic Dictionary of the Syriac Heritage, published by Gorgias Press on behalf of the Beth Marudtho: The Syriac Institute. e-GEDSH is the result of the collaborative efforts of many scholars. The encyclopedia currently holds xxx entries written by yyy contributors. This digital edition is implemented on the Srophé App platform using TEI XML, eXist-db, and linked open data technologies.

Can we dynamically replace the xxx above with a count of div type="entry"?
Can we dynamically replace the yyy above with a count of p elements at /TEI/text[1]/front[1]/div[3]?

**Comment by dlschwartz** [comment]
George prefers block justified text

**Comment by wsalesky** [comment]
@dlschwartz Added. You may close if you approve.

**Comment by dlschwartz** [comment]
Can we have the title and body of the blurb line up on the far left. The font size and weight set the title off enough and I think this will help distinguish things a bit more from the list of editors below. Then I thing we're in good shape.

**Comment by wsalesky** [comment]
@dlschwartz done!
