### ISSUE TITLE
Making of e-GEDSH

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#216]
@wsalesky I went ahead and created the div for the text we will add on the making of the electronic edition. The div contains a head, byline, idno type="uri" and idno type="front". I've numbered it where I would like it to appear in the front matter on the landing page and in browse. Right now it only has lorem ipsum but hopefully Dave and I will add the real text this afternoon. You might not need to do anything manually to make this section appear in the proper places but I wanted to let you know that I've added this just in case you do.

**Comment by dlschwartz** [comment]
The full text is now up on Github.

**Comment by wsalesky** [comment]
@dlschwartz  Here it is: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Making-e-GEDSH
Close if it looks good to you.

**Comment by dlschwartz** [comment]
Looks great. Only one more thing needed.  This should show on the landing page among the front matter: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/index.html.

**Comment by wsalesky** [comment]
Before or after "The Making of the Gorgias Encyclopedic Dictionary of the Syriac Heritage " ?

**Comment by dlschwartz** [comment]
I see it there now. I think it belongs before since introductions to newer editions generally appear before the original introductions. George might feel differently but for now this is how I think it should be. Looks great. Thanks. I'll close this out.
