### ISSUE TITLE
Add browse entries hyperlink to right column of landing page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#219]
@wsalesky It seems incomplete to have no link to the entries between the front matter and the back matter on the landing page. Can we add the text "Browse Entries" in the same font, etc. as the "Front Matter" and "Back Matter" on the right hand side of the landing page. That should have a link to http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html

**Comment by wsalesky** [comment]
Done.

**Comment by dlschwartz** [comment]
@wsalesky I had been thinking that this would appear without a bullet point but rather just the heading with a hyperlink. Now that I see this, I think that might look a bit odd. This looks better. But, perhaps we should change it to

**Entries**
- Browse all entries

I think that will work well.

**Comment by wsalesky** [comment]
Done.
