### ISSUE TITLE
Redo

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#22]
```Hand Corrections Added alt order name for Vaschalde, fixed an issue with <ref
rend="bold">ʿ</ref>```

                    <idno type="althead" subtype="altorder">Arthur Adolphe Vaschalde, C.S.B.</idno>
```

**Comment by davidamichelson** [comment]
@wsalesky Can you let me know when you are done please and I will redo this commit: 6633b43

Thanks

**Comment by wsalesky** [comment]
I updated the master branch. Please edit the copy in the data/tei directory.

**Comment by davidamichelson** [comment]
Thanks! Next up please focus on #16 if you could finish that by Tuesday that would be great please!

**Comment by davidamichelson** [comment]
Fixed these.
