### ISSUE TITLE
#/Next/All at bottom of browse

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#221]
@wsalesky The option to choose[#]/Next/All appears at the top and bottom of search results but appears only at the top of the browse results. Can we add that to the bottom of the browse page?
Compare: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html
With: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?q=brock

**Comment by wsalesky** [comment]
Done.
