### ISSUE TITLE
Browse formatting

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#226]
@wsalesky The front and back browse entries buttons have a slightly different display. For the front, the gray box sits above the first entry. For the back, it sits beside it and tweaks the nesting of the maps section. I think the back is arranged in the same way as the individual letters but should probably be arranged like the front. See the difference here: 
![front](https://user-images.githubusercontent.com/4984270/39251246-6d5e30b4-4868-11e8-8152-788ef990b0c4.JPG)
![back](https://user-images.githubusercontent.com/4984270/39251260-73bfd318-4868-11e8-9a09-f1408f1d9d2d.JPG)

**Comment by wsalesky** [comment]
@dlschwartz  Fixed. Reopen if it doesn't look right.
