### ISSUE TITLE
Browse box on left

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#231]
@wsalesky George would like "Front Matter" and "Back Matter" instead of "Front" and "Back". Thanks.

**Comment by wsalesky** [comment]
@dlschwartz Want me to change it on the browse page as well? http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/browse.html

**Comment by dlschwartz** [comment]
@wsalesky Good question. Yes, I suppose so. George wants it in one place and we should be consistent. Thanks.

**Comment by wsalesky** [comment]
Done.
