### ISSUE TITLE
URI matching

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#24]
@wsalesky, @davidamichelson asked me to send [this](https://docs.google.com/spreadsheets/d/1EKN3wfSKCTC5QbNRmHlKTiDvNT0DjMcsk-3VKvdSEH8/edit#gid=0) to you. I've gone through the sheet and chosen the correct URI for entries that did not need any investigation. Ute will need to check the rest manually. By my rough count it only leaves about 60 which is amazing! Can you please put these into the eGEDSH document? Thank you!
P.S. I looked for an existing issue on this topic and didn't find one. Sorry if I've duplicated issues for this.

**Comment by dlschwartz** [comment]
I think this should have come under issue #16. I tried to reopen it and merge the issues but I don't know how.

**Comment by davidamichelson** [comment]
Wow! Thanks Dan. @wsalesky just to be clear, please use this sheet to find and replace remaining tei:refs that do not have a @target 

One FYI, when you insert the URIS, Please DO NOT regularize the text nodes or anything, keep them as is (matching on them with typos in them) and we will ask Ute to fix the typos there later

**Comment by davidamichelson** [comment]
@wsalesky is there an update on this?

**Comment by wsalesky** [comment]
@davidamichelson sorry, I've been slammed this week. I will try to get these updated tonight.

**Comment by wsalesky** [comment]
Okay, here are the updates:
https://github.com/srophe/e-gedsh/tree/issue24
