### ISSUE TITLE
Purchase Print Link

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#240]
@wsalesky George would like a link to the Gorgias Press page where people can buy the print edition. That link is: https://www.gorgiaspress.com/gorgias-encyclopedic-dictionary-of-the-syriac-heritage-students-and-scholars

He thought that maybe it could go at the top between search and the Beth Mardutho link. The problem is that this needs some text to make the link meaningful. He suggested "Purchase the Printed Edition." I think this is too much for that top section. George then suggest the right-side menu. That would perhaps look something like this 
![purchase](https://user-images.githubusercontent.com/4984270/39488554-48dba03e-4d48-11e8-874c-dc8eb5d93e47.JPG)

I'm alright with this but if your eye for design suggests something else, please let me know.

**Comment by dlschwartz** [comment]
@wsalesky Dave has an idea to float by George. I'll clarify shortly.

**Comment by dlschwartz** [comment]
@wsalesky Alright, Dave has made the following suggestion and George finds it satisfactory. Can we add a button to appear to the right of the TEI button wherever it appears in e-GEDSH that looks something like "📖 Purchase" and contains a link to open in a new tab that goes here: https://www.gorgiaspress.com/gorgias-encyclopedic-dictionary-of-the-syriac-heritage-students-and-scholars. If you think this icon looks alright, I'm good with that. If you think it would be preferable to swap it out with something else, that would be fine too. As always, we value you eye for design.

**Comment by wsalesky** [comment]
Okay, I will see what I can find in terms of icons.

**Comment by wsalesky** [comment]
Can I use this icon: https://www.w3schools.com/icons/tryit.asp?filename=trybs_ref_glyph_book

It is already in the bootstrap package and as a font it is endlessly scaleable.

**Comment by dlschwartz** [comment]
Great, that sounds like a perfect solution. Thanks.

**Comment by wsalesky** [comment]
What would you like in the popup? 'Purchase a copy of the print edition' ?

**Comment by dlschwartz** [comment]
Oh yeah, I forgot about the popup. That's great since we don't want to take up too much space. Let's go with 'Purchase a copy of the printed edition'.

**Comment by wsalesky** [comment]
Added.

**Comment by davidamichelson** [comment]
Looks perfect. Great work.

**Comment by dlschwartz** [comment]
@wsalesky George would also like this on the landing page. Is there any chance it could go here (see image) and still have the popup? If so, I propose that we remove it from it's current position and simply put it in the very top banner throughout e-GEDSH.
![newpurchase](https://user-images.githubusercontent.com/4984270/39582132-e365c272-4eb2-11e8-931a-c0634dd8c419.JPG)

**Comment by davidamichelson** [comment]
I would prefer to keep the button where it is on the entry pages not in the
head, it matches the style and is unobrusive. For the landing page let's
add it separate.

**Comment by wsalesky** [comment]
Where would you like to see it on the landing page? My preference would be right column above 'Front Matter'

**Comment by dlschwartz** [comment]
George had initially suggested that it could go below the "Back Matter", see image at the top of this issue. I have an equal dislike for above the Front Matter and below the Back Matter. I guess that means I'm fine with either. @davidamichelson what's your preference?

**Comment by dlschwartz** [comment]
@wsalesky Let's go with your idea and add the icon w/ popup about the "Front Matter". Thanks.

**Comment by dlschwartz** [comment]
@wsalesky Dave has come up with what I think is a solid suggestion. Rather than put the button on the landing page, let's try the following below the "Back Matter" section.

Equivalent to the headings (front, entries, back) we would like a heading that reads "Printed Edition". Below that, we would like a bullet point with the text "Available from Gorgias Press" with a hyperlink opening in a new tab that goes here: https://www.gorgiaspress.com/gorgias-encyclopedic-dictionary-of-the-syriac-heritage-students-and-scholars. 

Let's hope this works for everyone. Thanks Winona.

**Comment by davidamichelson** [comment]
Sorry @wsalesky but Senior Advisors needs to be plural now. Otherwise looks great!

**Comment by wsalesky** [comment]
opps, sorry. I'm distracted by our LOD troubles. (Soon to be resolved!)
