### ISSUE TITLE
push latest commits

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#242]
@wsalesky I made a couple of edits in the TEI (hopefully the last!). Whenever it's convenient to push those so I can see them in the html would be great. I'm not in a hurry. Thanks.

**Comment by dlschwartz** [comment]
@wsalesky I see the changes I made to the main document but I forgot to mention that I made a change to the e-GEDSH_figs document as well. Thanks.

**Comment by wsalesky** [comment]
Okay, I just pushed the e-GEDSH_figs document to the dev server.
