### ISSUE TITLE
Italics on "Making" page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#243]
@wsalesky In the first paragraph of the "Making" text (http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Making-e-GEDSH) there are two instances of `<hi rend="italic">Gorgias Encyclopedic Dictionary of the Syriac Heritage</hi>`. These don't appear in italics in the html. They're wrapped in refs which probably explains it. Thanks.

**Comment by wsalesky** [comment]
Fixed.
