### ISSUE TITLE
Space before comma in LOD box

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#245]
@wsalesky George noticed that there is an unwanted space between a last name and a comma before the first name in the LOD box. See related resources here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Qarabashi-Abd-al-Masih-Numan

**Comment by dlschwartz** [comment]
This might help

![image](https://user-images.githubusercontent.com/4984270/39551503-d03acb62-4e2a-11e8-9d49-e4199d097797.png)

**Comment by wsalesky** [comment]
@dlschwartz thanks, this is a problem with the linked data generation. I will take a look.

**Comment by wsalesky** [comment]
Fixed.
