### ISSUE TITLE
Switch "Author" to "Contributor" in search results

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#251]
@wsalesky George noticed that the results page for a contributor search gives the count total at the top left as "# matches for Author". http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?q=&author=kiraz&placeName=&persName=&bibl=&uri=. Given that this is a "contributor" search it would be good if we could change this to "# matches for Contributor". Thanks.

**Comment by wsalesky** [comment]
@dlschwartz The search results also have Author in the short record view in the results. Should I change that contributor also?
<img width="669" alt="screen shot 2018-05-08 at 10 54 28 am" src="https://user-images.githubusercontent.com/1168206/39764735-43875edc-52ae-11e8-8510-8cd2a7188ec6.png">
 See image

**Comment by dlschwartz** [comment]
@wsalesky Good eye. Yes, please do. Thanks!

**Comment by wsalesky** [comment]
@dlschwartz Done.

**Comment by dlschwartz** [comment]
@wsalesky  This change seems to have broken the contributor search. It looks like we're only getting returns for the front matter. A search for "kiraz" was turning up 80 results, now we get 3, all from the front matter: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?author=George%20A.%20Kiraz. All other searches for contributors I tried turned up 0 hits unless they are in a byline element in the front. Thanks.

**Comment by wsalesky** [comment]
Do a hard refresh please. We are having some issues with the index. I reindexed and it looks okay to me.

**Comment by dlschwartz** [comment]
Looks great. Thanks Winona.
