### ISSUE TITLE
Submit Linked Data Button

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#253]
@dlschwartz @jedwardwalters In light of wanting the LOD box to be open and not a closed Syriaca.org thing, how about a button at the bottom of the box, maybe in gray like the label at the top that says "Submit linked data." This button would take one to a contact form and about page which invites them to submit data marked up with Syriaca.org URIS?

**Comment by davidamichelson** [comment]
This would be for both gesdhs and corpus

**Comment by dlschwartz** [comment]
@davidamichelson @jedwardwalters @wsalesky Great idea. Do we have pages already that do those things in the way we want them to do those things?

**Comment by jedwardwalters** [comment]
I'm definitely in favor of this. We need to think about how to encode this. There are files already in the courpus we could test with links to HMML or the Vatican library manuscripts.

**Comment by davidamichelson** [comment]
Yes, but let's discuss on Monday

**Comment by davidamichelson** [comment]
Please update the text for the question mark button on both apps (GEDSH and Corpus):

"This sidebar provides links via Syriaca.org to additional resources beyond this record. We welcome your additions, please use the e-mail button on the right to submit additional links to Syriaca.org"

**Comment by wsalesky** [comment]
Added to dev for Corpus. When I get approval I will move it to Production.

**Comment by dlschwartz** [comment]
@davidamichelson How about "please use the e-mail button on the right to contact Syriaca.org about submitting additional links"?

**Comment by wsalesky** [comment]
@davidamichelson Yes, I will add that.

**Comment by davidamichelson** [comment]
Thanks!

**Comment by davidamichelson** [comment]
One fyi on this, the submit linked data button should send to the info@syriaca.org editors not the e-gedsh contact form editors.

**Comment by wsalesky** [comment]
Stale issue, was fixed a while ago.
