### ISSUE TITLE
How to Cite

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#255]
@wsalesky Ute would like to remove her middle initial from the How to Cite section. Also, we have an unnecessary comma in this section. In each paragraph we have "edited by," where we should have "edited by".  Also, it looks like the line spacing in the first (before expansion) paragraph is bigger than in the other (after expansion) paragraphs. Could we make that standard across all paragraphs. Thanks.

**Comment by wsalesky** [comment]
Updated.
