### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#256]
@wsalesky 
The count of contributors reads 0. 
On the right hand side, can we change the link "Browse all entries" to "Browse All Entries"?
Can we reduce the space between these headings and the following lists? It would emphasize the grouping a bit better.
![editors](https://user-images.githubusercontent.com/4984270/40240595-775fa7aa-5a7e-11e8-89c1-859103ae2cd5.PNG)

**Comment by wsalesky** [comment]
@dlschwartz Fixed. If you like the new spacing you may close the issue, otherwise let me know if you need more/less.

**Comment by dlschwartz** [comment]
@wsalesky This looks great to me. Thank you.
