### ISSUE TITLE
Update to How to Cite Box

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#257]
@wsalesky Okay there is a new Chicago Manual of style and it has better recommendations:

The first citation form stays the same.

For the second and third form, please remove the accessed date (I think we do want to keep this in other modules, so just remove for e-GEDSH please).

For the second and third form, please add the  static publisher information (so this will be the same in every citation, so you can hard code it in): (Gorgias Press, 2011; online ed. Beth Mardutho, 2018) and Gorgias Press, 2011; online ed. Beth Mardutho, 2018. Please note how this will also delete and move the comma to after the parenthesis in the second citation.

Lucas Van Rompay, “Aba,” in _Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition_, edited by Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay, https://gedsh.bethmardutho.org/Aba.

**Footnote Style Citation with Date:**

Lucas Van Rompay, “Aba,” in _Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition_, edited by Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay (Gorgias Press, 2011; online ed. Beth Mardutho, 2018), https://gedsh.bethmardutho.org/Aba.

**Bibliography Entry Citation:**

Van Rompay, Lucas. “Aba.” In _Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition_. Edited by Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay. Digital edition prepared by Ute Possekel and Daniel L. Schwartz. Gorgias Press, 2011; online ed. Beth Mardutho, 2018. https://gedsh.bethmardutho.org/Aba. 

A TEI-XML record with complete metadata is available at https://gedsh.bethmardutho.org/Aba/tei.

**Comment by davidamichelson** [comment]
Oh, one more change. Please add my name back in to the Bibliography as we are changing titles again.

So new version:

Bibliography Entry Citation:

Van Rompay, Lucas. “Aba.” In Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition. Edited by Sebastian P. Brock, Aaron M. Butts, George A. Kiraz and Lucas Van Rompay. Digital edition prepared by Ute Possekel, Daniel L. Schwartz, and David Michelson. Gorgias Press, 2011; online ed. Beth Mardutho, 2018. https://gedsh.bethmardutho.org/Aba.

**Comment by dlschwartz** [comment]
@wsalesky @davidamichelson Actually the names should be alphabetical, just like they are for the print editors on both the landing page and the citations: David Michelson, Ute Possekel, and Daniel L. Schwartz

**Comment by wsalesky** [comment]
@davidamichelson  @dlschwartz  Updated. Please check and close.

**Comment by davidamichelson** [comment]
Looks great!
