### ISSUE TITLE
editors on landing page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#259]
@wsalesky I think we have the final edits regarding the list of editors on the landing page. Thanks Winona. 

Digital Edition Editors
David A. Michelson, Vanderbilt University
Ute Possekel, Harvard University
Daniel L. Schwartz, Texas A&M University

Senior Programmer
Winona Salesky

Senior Advisor
Peter R. L. Brown, Princeton University

**Comment by wsalesky** [comment]
Done.
