### ISSUE TITLE
Final URI Matching and Updating

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#26]
Following issue #24 
There remains the following URI work for gedsh internal URIs
1. Some of the URIS in this list still need matching by Ute: https://docs.google.com/spreadsheets/d/1EKN3wfSKCTC5QbNRmHlKTiDvNT0DjMcsk-3VKvdSEH8/edit#gid=0
2. Some of the URIS in this list were matched but have Typos: https://docs.google.com/spreadsheets/d/1EKN3wfSKCTC5QbNRmHlKTiDvNT0DjMcsk-3VKvdSEH8/edit#gid=0
3. When all URIS have been matched, we should run a script that will look at the text node of each tei:ref and using the @target URI it will compare it with the text nodes of all idnos of the URI and in the case where there is not match it will insert a new tei:idno[@type="althead'] with the textnode immediately before note[@type]

**Comment by dlschwartz** [comment]
@upossekel and @davidamichelson This is a really old Github issue. I don't know if we still need to do any work on this or not. I don't see any problems. Ute, did you check the ref target URIs for cross references to GEDSH headwords in the body of articles? If so, I recommend that we close this issue. Thanks.

**Comment by upossekel** [comment]
Yes, I generally checked these things.

**Comment by dlschwartz** [comment]
Very good. I'll close this issue. If we could all be diligent about noting any bad links that would be great. Thanks.
