### ISSUE TITLE
Contact info on landing page of e-gedsh

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#260]
Please add a contact button at the bottom of the landing page in the left column under the names of the senior advisors. This button should create an e-mail to George, Dan, Dave

**Comment by wsalesky** [comment]
@davidamichelson does e-GEDSH have a google email? Can you send me the details via email?

**Comment by davidamichelson** [comment]
I will make one

**Comment by davidamichelson** [comment]
I think we should put a link to the contact form at the bottom of the landing page underneath Peter Brown’s name.
Senior Advisor
[indent] Peter R. L. Brown, Princeton University 

[no indent] Contact e-GEDSH [in blue as a live link]



The form itself will have the following text and fields:

“Contact the e-GEDSH editorial team:
Name
e-mail
subject
comment
send”

**Comment by wsalesky** [comment]
These should now be functional on the production server, please let me know if you did not @davidamichelson  @dlschwartz  receive an email from e-GEDSH.
