### ISSUE TITLE
Rename xml file and push

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#262]
@wsalesky I see we have GEDSH on production, excellent! I forgot that I wanted to do a couple of things in advance of that. First is that I wanted to remove the comments. I've saved them in a branch on Github (withComments) so that we can access them when we want but I've removed them from the master branch with this commit: https://github.com/srophe/e-gedsh/commit/bfe056830052d9deacb153223b9effdd2e78e5b3. I also wanted to rename the xml file. We discussed this and I seem to recall you saying some version of 'make sure you avoid doing x.' Of course, I can't remember what x was and rather than messing things up at a critical time I thought I would ask you to do this. Can you rename the xml file from 'egesdh-version-0-1.xml' to 'eGEDSH-1.0.xml'? Then you can push this to dev and production. Thanks Winona.

**Comment by wsalesky** [comment]
Done, and pushed to production.
