### ISSUE TITLE
Font Dev Branch

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#265]
Could you please leave production server with current font but change Dev server to the sans-serif font we discussed. Once we can compare the two we will send to the editorial team to get their opinon.

**Comment by wsalesky** [comment]
Done.

**Comment by davidamichelson** [comment]
Thanks! Once the other comparison issue is also on Dev, I will send them
both out.

**Comment by wsalesky** [comment]
@davidamichelson closing as a stale issue.
