### ISSUE TITLE
Dev Server Branch for Change to Browse

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#266]
On Browse and Search, we would like to compare the current version (on Prod) with a new version on Dev where we eliminate the title "Contributor"

Current:

Aba (ca. 400)
_Contributor: Lucas Van Rompay_ 
URI: https://gedsh.bethmardutho.org/Aba

New for Dev Only:

Aba (ca. 400)
_Lucas Van Rompay_ 
URI: https://gedsh.bethmardutho.org/Aba

Could you please make this change to Dev and we can compare with the current on Production?

Thanks,
Dave

**Comment by wsalesky** [comment]
Ready for comparing.

**Comment by wsalesky** [comment]
@davidamichelson closing as a stale issue.
