### ISSUE TITLE
Search box is two sizes

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#267]
@wsalesky The search box is slightly two different sizes, the outline around the magnifying glass and gear icons is just a hair larger than around the "search" part of the box, so the line breaks at top (maybe) and bottom (for sure). Is this easy to fix?

**Comment by davidamichelson** [comment]
Mac OS Firefox and a PC for Ute not sure what browser, will ask

**Comment by davidamichelson** [comment]
On iOS it looks fine

**Comment by wsalesky** [comment]
@davidamichelson I'm having trouble seeing the problem, but I made a few changes on the dev server. Can you check and see if it looks resolved?

**Comment by wsalesky** [comment]
@davidamichelson Is this resolved?

**Comment by wsalesky** [comment]
@davidamichelson closing as a stale issue.
