### ISSUE TITLE
Breakout articles into new xml files

### ISSUE THREAD

**Issue by wsalesky** [srophe/e-gedsh#268]

**Comment by wsalesky** [comment]
@dlschwartz Can you take a look at the data in this branch?
https://github.com/srophe/e-gedsh/tree/breakoutData

 Let me know if we need to make any changes. In the meantime I will do some testing regarding speed. 
Thanks!

**Comment by dlschwartz** [comment]
@wsalesky this looks great to me. Thanks so much! I look forward to hearing about possible improvements to the speed. 

@davidamichelson can you take a look at this too. I'd like us both to sign off on it. I've erred on the side of too much information in the header. All of the editors and respStmts get repeated in the titleStmt and the seriesStmt. The print editors appear again in the sourceDesc. This isn't strictly necessary but it is abundantly clear if anyone were to have concerns.

**Comment by dlschwartz** [comment]
@wsalesky, just an FYI. I'm not sure whether @davidamichelson has signed off yet on the headers in breakoutData, but I wanted you to know that I have made changes to two files https://github.com/srophe/e-gedsh/commit/1b1eb7e937194ce4024f37b4635af0880ffe9cf6 to correct errors that people recently brought to our attention. If we go ahead and use the files here in breakoutData branch this shouldn't require any additional attention. If we need to re-run the conversion of the old single file, we'll need to put these changes back in. Thanks.

**Comment by wsalesky** [comment]
@davidamichelson Can we merge this branch into master? What do you think?

**Comment by wsalesky** [comment]
Done and ready to merge, pending review by @dlschwartz

**Comment by dlschwartz** [comment]
@wsalesky did you make changes to the header today? I don't see that commit.

**Comment by wsalesky** [comment]
@dlschwartz no changes. was i supposed to? i was a little distracted at the meeting. (sorry!)

**Comment by dlschwartz** [comment]
@wsalesky no worries. Let's loop @davidamichelson in again. I must have misunderstood what he said today. I thought Dave wanted to add the following to `<titleStmt>` and `<seriesStmt>`:  `<editor role="print-edition"
                    ref="http://syriaca.org/documentation/editors.xml#gkiraz">George A. Kiraz</editor>` so that it appeared alongside what already appears: `<editor role="general"
                    ref="http://syriaca.org/documentation/editors.xml#gkiraz">George A. Kiraz</editor>`. 

I thought that the stated reason was to bring the TEI header into line with what appears on the site: https://gedsh.bethmardutho.org/index.html. However, the site lists exactly what we already have in the header, that George is listed as the "General Editor" but not among the "Print Edition Editors". 

Also, I thought there was a point to the current practice. George is the general editor of both the print and electronic.

@davidamichelson can you clarify what changes you wanted to make to the header. Thanks.

**Comment by davidamichelson** [comment]
Okay, sorry the mistake was mine. I see that George is listed on the index.html page as only General, not Print. So leave the list of tei:editor as is.

I would change the following:

```<edition n="1.0">Electronic Edition Draft Version 1.0</edition>```

This should read

            ```<edition n="1.5">Electronic Edition Version 1.5</edition>```

It is no longer draft, and I would distinguish the individual file version from the 1.0 but of course this is not a 2.0

Sorry again for the delay.

**Comment by davidamichelson** [comment]
@wsalesky @dlschwartz Just letting you know I replied.

**Comment by dlschwartz** [comment]
@davidamichelson Thanks Dave. @wsalesky I will make that edition change and let you know when it's ready.

**Comment by dlschwartz** [comment]
@wsalesky This commit https://github.com/srophe/srophe-eXist-app/commit/7ff515cc6a2606dacc682214a7cc3bd6919e9d05 finalized the breaking out of the articles. Thanks.
