### ISSUE TITLE
Troubleshoot display of maps and images in GEDSH

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#272]

**Comment by wsalesky** [comment]
Error: 
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://iiif.dh.tamu.edu/iiif/2/syriaca%2FRompay-map-I-final-combined.tif/info.json with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Also:

**Comment by wsalesky** [comment]
The IIIF server needs to enable CORS request from our server.

**Comment by dlschwartz** [comment]
@wsalesky Oguzhan tells me that he has made changes to the sites config file (no additional detail). I do see that the links are updated in the tei http://gedsh.dh.tamu.edu/Maps/tei that loaded. This didn't automatically fix anything. Let me know if you can work with this or I need to go back to Oguzhan. Thanks.

**Comment by wsalesky** [comment]
Fixed
