### ISSUE TITLE
listBibl

### ISSUE THREAD

**Issue by wsalesky** [srophe/e-gedsh#3]
@davidamichelson would it be possible to use `listBibl` under the `div@type="bibliography"`? It would ease display, and I think add some structural clarity. We have the `bibl` element showing up in many different ways, and when it is in a `p` it needs to be displayed inline, in this case the display should really be a list, and I think `listBibl` would be appropriate.

**Comment by davidamichelson** [comment]
Yes, this will go in issue #5
