### ISSUE TITLE
UI for e-gedsh is down

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#31]
@wsalesky It looks like e-gesdh is down?

Could you please get it back up tomorrow before we meet? We would like to have the User Interface revised by later this week.

This is the link that does not work:
http://wwwb.library.vanderbilt.edu/gedesh/entry.html?id=http://gedsh.bethmardutho.org/Aba-I

**Comment by wsalesky** [comment]
Try this uri:
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Aba

**Comment by wsalesky** [comment]
Home page (I seem to be confused about how to spell gedsh/gedesh? let me know which is correct and we can redepoly under the right name):
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/index.html

**Comment by davidamichelson** [comment]
Thanks! FYI it should be "gedsh"

**Comment by wsalesky** [comment]
Okay, should I lose the 'e-' or is it fine as is?

**Comment by dlschwartz** [comment]
I like "e-gedsh".
dls

On Tue, Oct 18, 2016 at 12:20 PM, Winona Salesky <notifications@github.com>
wrote:

> Okay, should I lose the 'e-' or is it fine as is?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_e-2Dgedsh_issues_31-23issuecomment-2D254577463&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=eNlyQF3A7GKvA61SoGbhxPBf92e_gKQqeuCPadAVFfc&s=kjPR4wv7JtIY0SjLJLlTmIY6fPdosgkGpp5kMQQ5uYg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzv1sGebFNmnpEdGOFraVDo5R2l4-2Dks5q1P-5FIgaJpZM4KZ9-2DM&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=eNlyQF3A7GKvA61SoGbhxPBf92e_gKQqeuCPadAVFfc&s=ae_hKiqnh_BW1sNR-viF5w-x8OKzRi5Fo2SYTp8a8qE&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by davidamichelson** [comment]
yes pls keep the e-
