### ISSUE TITLE
HTML Styling

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#32]
Please make the following adjustments to the template. Examples refer to http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Aba-I

- Please label tei:/TEI/text/body/div/byline/persName with "Author" and mark in italics

example: "Author: _L. Van Rompay_"

- Please mark italics for all @rend[type="italic']; occurs as tei:hi/@rend[type="italic'] and  tei:title/@rend[tyep="italic']

example= _mpaššqānā_
example= _Histoire de Mar-Jabalaha, de trois autres patriarches, d’un prêtre et de deux laïques, nestoriens_

- please find and render all @rend="superscript" as superscript (HTML5:sup?)

- please check for any other @rend (I don't think there are any).

- For now (we may switch this later to optimize for the webe), please use a serif font such as Times. This will make comparison with the print version easiest. You could check the PDF to see what font was used.

- for all tei:listBibl//bibl please remove the bullets and instead list with hanging indent as in PDF.

**Comment by dlschwartz** [comment]
We have @rend="bold" for the cross references. The schema allows
@rend="underline" in the <hi> element but I don't find this in the xml. I'm
not sure why I would have included it in the schema though unless it
appeared somewhere. Perhaps I should remove that option.
Dan

On Tue, Oct 18, 2016 at 2:48 PM, David Michelson <notifications@github.com>
wrote:

> Please make the following adjustments to the template. Examples refer to
> http://wwwb.library.vanderbilt.edu/exist/apps/e-
> gedsh/entry.html?id=http://gedsh.bethmardutho.org/Aba-I
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__wwwb.library.vanderbilt.edu_exist_apps_e-2Dgedsh_entry.html-3Fid-3Dhttp-3A__gedsh.bethmardutho.org_Aba-2DI&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=htAsNV7zod9jXeV4tMUXOSzl8uRb0OT4-AAFyv3o_2k&s=r3mpMKg3LkaweBPS0SojtmxYZIWpFwvqjLnNVCVWtqE&e=>
>
>    - Please label tei:/TEI/text/body/div/byline/persName with "Author"
>    and mark in italics
>
> example: "Author: *L. Van Rompay*"
>
>    - Please mark italics for all @rend
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rend&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=htAsNV7zod9jXeV4tMUXOSzl8uRb0OT4-AAFyv3o_2k&s=aZ-kX_vBs3KsXdt7aKpNgbizTvA5Ldk-IdGKImO0304&e=>[type="italic'];
>    occurs as tei:hi/@rend
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rend&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=htAsNV7zod9jXeV4tMUXOSzl8uRb0OT4-AAFyv3o_2k&s=aZ-kX_vBs3KsXdt7aKpNgbizTvA5Ldk-IdGKImO0304&e=>[type="italic']
>    and all tei:title/@rend
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rend&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=htAsNV7zod9jXeV4tMUXOSzl8uRb0OT4-AAFyv3o_2k&s=aZ-kX_vBs3KsXdt7aKpNgbizTvA5Ldk-IdGKImO0304&e=>
>    [tyep="italic']
>
> example= *mpaššqānā*
> example= *Histoire de Mar-Jabalaha, de trois autres patriarches, d’un
> prêtre et de deux laïques, nestoriens*
>
>    -
>
>    please find and render all @rend
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rend&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=htAsNV7zod9jXeV4tMUXOSzl8uRb0OT4-AAFyv3o_2k&s=aZ-kX_vBs3KsXdt7aKpNgbizTvA5Ldk-IdGKImO0304&e=>="superscript"
>    as superscript (HTML5:sup?)
>    -
>
>    please check for any other @rend
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rend&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=htAsNV7zod9jXeV4tMUXOSzl8uRb0OT4-AAFyv3o_2k&s=aZ-kX_vBs3KsXdt7aKpNgbizTvA5Ldk-IdGKImO0304&e=>
>    (I don't think there are any).
>    -
>
>    For now (we may switch this later to optimize for the webe), please
>    use a serif font such as Times. This will make comparison with the print
>    version easiest. You could check the PDF to see what font was used.
>    -
>
>    for all tei:listBibl//bibl please remove the bullets and instead list
>    with hanging indent as in PDF.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_e-2Dgedsh_issues_32&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=htAsNV7zod9jXeV4tMUXOSzl8uRb0OT4-AAFyv3o_2k&s=e6DEhxA8XUmSK-g6QA5nb-tgn7OHLMYS6p93LaSuoqc&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzr-2Dc55rzwuskPHDjTLaNlC6-5FM29Eks5q1SKWgaJpZM4KaNoS&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=htAsNV7zod9jXeV4tMUXOSzl8uRb0OT4-AAFyv3o_2k&s=Fmgn1HLBZwsn7k6nFOCdXk-gb_Mf8Q1mJrr0e-DR1OE&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by davidamichelson** [comment]
On Tue, Oct 18, 2016 at 4:25 PM, Daniel Schwartz <notifications@github.com>
wrote:

> We have @rend="bold" for the cross references. The schema allows
> @rend="underline" in the <hi> element but I don't find this in the xml. I'm
> not sure why I would have included it in the schema though unless it
> appeared somewhere. Perhaps I should remove that option.
> Dan
>

Underline was there in the data and then I replaced it with unicode
characters. You could remove it from schema

**Comment by dlschwartz** [comment]
Very good

On Tue, Oct 18, 2016 at 4:34 PM, David Michelson <notifications@github.com>
wrote:

> On Tue, Oct 18, 2016 at 4:25 PM, Daniel Schwartz <notifications@github.com
> >
> wrote:
>
> > We have @rend="bold" for the cross references. The schema allows
> > @rend="underline" in the <hi> element but I don't find this in the xml.
> I'm
> > not sure why I would have included it in the schema though unless it
> > appeared somewhere. Perhaps I should remove that option.
> > Dan
> >
>
> Underline was there in the data and then I replaced it with unicode
> characters. You could remove it from schema
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_e-2Dgedsh_issues_32-23issuecomment-2D254646184&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=lN1gUK-MJzG60xBNSIJTwv0v16fNXMss8ewlW7xjBFM&s=pxgMdeSTLPWbRij3orUbIXd6xQt2qX0j2c3V3tA1ERg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzvOZ-5F-5FSUlGFCoWS6rrgbr1Q-5FA6mqks5q1TtqgaJpZM4KaNoS&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=lN1gUK-MJzG60xBNSIJTwv0v16fNXMss8ewlW7xjBFM&s=ZfsjgbVmYyL_eS5XfrrG0bcRaIAqIL5Ztr55IThyfT0&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by davidamichelson** [comment]
@wsalesky As a temporary aid to proofing, could the cross reference links be marked in red? (?Not sure if the link color is something I set in my browser of part of your code) but in my view they are blue which does not stand out enough from the black prose.

**Comment by wsalesky** [comment]
so any link that starts with 'http://gedsh.bethmardutho.org/' should be red?

**Comment by davidamichelson** [comment]
Great work @wsalesky. Two small tweaks. 

The Author name is not displaying in italics (it is not rend=italic in the TEI, we could mark it that way there if that would be the best fix).

Please put the ab type="infobox" on the same line as tei:head

**Comment by wsalesky** [comment]
Added italics.
