### ISSUE TITLE
License info on HTML pages needs changing.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#37]
Currently reads:

Creative Commons License This work is licensed under a Creative Commons Attribution 3.0 Unported License.
Copyright Vanderbilt University, Princeton University, and the Contributor(s), 2014. 

Should read:

Creative Commons License This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 license (CC BY-NC 4.0) [href=https://creativecommons.org/licenses/by-nc/4.0/].
Copyright © 2011 Beth Mardutho: The Syriac Institute.

**Comment by davidamichelson** [comment]
@wsalesk you are too great!!!

Sorry one more thing. Please change the icon to the CC-BY-NC Icon here https://creativecommons.org/about/downloads/

**Comment by davidamichelson** [comment]
Also the license link appears to be relative not absolute so does not resolve. Thanks

**Comment by wsalesky** [comment]
bad copy past error!
