### ISSUE TITLE
Color of background for e-gedsh

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#38]
Should we try to match the color scheme on the print edition? Might help make our editors happy?

https://www.google.com/imgres?imgurl=http://t1.gstatic.com/images%3Fq%3Dtbn:ANd9GcRlPXZLLbWTbCA8oWNst79yeg0KjS5GlP-0ZZjpz2q1PWZyCDcZ&imgrefurl=http://books.google.com/books/about/Gorgias_Encyclopedic_Dictionary_of_the_S.html%3Fid%3D8H3xAwAACAAJ%26source%3Dkp_cover&h=1080&w=822&tbnid=hbBQAAen-z0oKM:&tbnh=160&tbnw=122&docid=RbGC7wQOD2fNNM&itg=1&usg=__1gfTkjD9N3q296FHxhP6EUfGvjY=&sa=X&ved=0ahUKEwi84rXjw-nPAhUGLSYKHTZID14Q_B0IZDAK

**Comment by davidamichelson** [comment]
Let's save that for a time when we get feedback from them. We can suggest
it then.

**Comment by wsalesky** [comment]
This issue can be closed
