### ISSUE TITLE
another thought on abbreviations: provide link to list?

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#40]
Another thought on the subject of abbreviations occurred to me. If we don't want to change them - and I can see good reasons to keep the text exactly as is - we might consider adding a link on each article page (maybe in upper right, where at present there is the item 'links to other article'; but clearly distinguished from that). This might bring the reader to both the list of common abbreviations - so the reader can figure out what Ch. of E. is, as well as to a list of bibliographic abbreviations.
For abbreviated book/article titles, one could consider making these clickable so as to link directly with the full bibliographic information, but perhaps that would be too complicated, or undesirable for other reasons. 
Just a thought.
Ute

**Comment by dlschwartz** [comment]
@upossekel I have gone through the document and wrapped all of the abbreviations  in abbr elements (except the shortened titles for frequently quoted works which we can consider doing later). This will allow us to easily add just this capability you have suggested. As you edit, you can check abbreviations and make sure they are wrapped in an abbr element.

**Comment by davidamichelson** [comment]
Great ideas, perhaps for the common prose abbreviations in the info boxes such as Cath. we might want to expand but for the journal titles just make the abbreviations a clickable link which expands which allows us to keep the bibliography as is?

**Comment by dlschwartz** [comment]
Ute,

On second thought, I can just do this with advanced find and replace this
afternoon. It will only take me a few minutes.

This reminds me of something else that Dave didn't puy in the work flow. If
you encounter a typo in the print edition, go to the XML and wrap the error
in a sic element. Then put in the correct spelling wrapped in a corr
element. We will only show the corr but this will allow us to give George a
nice list of typos that need fixing in the case of a second edition.

You should take a look at these elements in the TEI guidelines: sic, corr,
reg, orig.

Dan

On Oct 22, 2016 10:00 AM, "Daniel Schwartz" <daniel.schwartz@tamu.edu>
wrote:

Ute,
You should work without making any changes to abbreviations at the moment.
The proper way to do this would be to wrap the abbreviation in an orig
element followed immediately by rhe expansion in a reg element. This would
allow for the display of either while maintaining the encoding of exactly
what appears in the print edition. If we go this route, we will write a
script to make this change automatically  (the abbreviations and the
expansions are already in the front matter of the TEI doc. Dave and I can
discuss the script on Tuesday and get back to you then. Thanks Ute. This is
a good thing to think about at an early stage.

Best,
Dan

**Comment by dlschwartz** [comment]
Ute,
You should work without making any changes to abbreviations at the moment.
The proper way to do this would be to wrap the abbreviation in an orig
element followed immediately by rhe expansion in a reg element. This would
allow for the display of either while maintaining the encoding of exactly
what appears in the print edition. If we go this route, we will write a
script to make this change automatically  (the abbreviations and the
expansions are already in the front matter of the TEI doc. Dave and I can
discuss the script on Tuesday and get back to you then. Thanks Ute. This is
a good thing to think about at an early stage.

Best,
Dan
