### ISSUE TITLE
bibliography should appear left justified

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#47]
In the display of the bibliography, it might be preferable to have this left-justified rather than inserted. This is not urgent, but we might want to do this for the final version.

**Comment by dlschwartz** [comment]
We discussed in our meeting today and there was a consensus that we liked having the bibliography offset as it defines the text and bibliography more clearly. Please feel free to lobby for this again @upossekel  when we get further into discussing display issue but for now let's hold off on making any changes here. Thanks.
