### ISSUE TITLE
forward function brings up previous entry

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#49]
The 'forward' function of e-GEDSH brings one to the previous item, at least in various entries under A. The 'backward' function also does not always work flawlessly.

To have this work properly would be high-priority for me, as it is a bit tedious to go from one entry to the next by going through the alphabetical list.

Thanks!

**Comment by wsalesky** [comment]
I think this commit fixes the issue. 
https://github.com/srophe/e-gedsh-app/commit/433b99c9b9dd19b8ee0ea8a86acdc57466d28f8b

Please let me know if you continue to have trouble. (post example entries that have problems). Thanks!
