### ISSUE TITLE
Transformations to Initial TEI: listBibl and tei:hi to tei:title

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#5]
@wsalesky Okay there is now a complete file with all articles that is also well-formed and valid TEI here: https://github.com/srophe/e-gedsh/blob/master/egesdh-version-0-1.xml

Could you please make the following transformations for me please?

1. Related to issue https://github.com/srophe/e-gedsh/issues/3 Please wrap the bibl lists in a listBibl. This can be done by wrapping everything between div[@type ="entry]/bibl[1] and div[@type ="entry]/byline which will always proceed the last tei:bibl. Thus is also the only use of tei:bibl elements so you should be able to write the script safely without finding bibl elements anywhere else. It is also the case that all or most of the time div[@type ="entry]/bibl[1] also has the attribute value n="1" and directly follows a tei:p element, but there may be places where the data is inconsistent.

**Comment by davidamichelson** [comment]
Updated this to add in tei:title/@rend="italic"

**Comment by wsalesky** [comment]
New data here:
https://github.com/srophe/e-gedsh/tree/issue5

I see that listBibl does not validate, although the TEI website does allow listBibl contained by a div. We may need to add this to our list of schema updates.

**Comment by davidamichelson** [comment]
Okay I just updated the samplefile to test this out and there are a few issues.

1. It looks like TEI only allows tei:head once per listBibl and as the first element. So to be compliant we need to change the structure to use nesting of listbibls inside listbibls. See the sample xml file. Can you add this transformation?

2. Also, in our structure, we actually have some sub-sub-section labels in the bibliography (search for ```<label type="subsubsection">```). These will need to be converted to tei:head and also get a nested listBibl.

3. As an FYI there are also tei:labels in the body, I'll post separately about them in issue #7 but please becareful not to affect them in these scripts.

**Comment by wsalesky** [comment]
The current script nests the listBibl if there are labels, so each label is the head of a single listBibl, nested in the main listBibl. You can see it on the first entry, on this branch: 
https://github.com/srophe/e-gedsh/tree/issue5

Let me know if you think the subsections should be handled differently.

**Comment by wsalesky** [comment]
Here is what it looks like transformed:
```

<listBibl>
    <listBibl>
        <head>Primary Sources</head>
        <bibl>P.  Bedjan, <title rend="italic">Histoire de Mar-Jabalaha, de trois autres
                patriarches, d’un prêtre et de deux laïques, nestoriens</title> (1895; repr. as
                <title rend="italic">The history of Mar Jab-Alaha and Rabban Sauma</title>, 2007),
            206–87. (Syr. of Life of Aba)</bibl>
        <bibl>Braun, <title rend="italic">Synodicon Orientale</title>, 93–145.</bibl>
        <bibl>idem, <title rend="italic">Ausgewählte Akten persischer Märtyrer</title>, 188–220. (GT
            of Life of Aba)</bibl>
        <bibl>Chabot, <title rend="italic">Synodicon Orientale</title>, 68–95 (Syr.), 318–51
            (FT).</bibl>
        <bibl>A.  Scher, <title rend="italic">Histoire nestorienne inédite (Chronique de
                Séert)</title>, vol. 2.1 (PO 7; 1909), 154–71.</bibl>
    </listBibl>
    <listBibl>
        <head>Secondary Sources</head>
        <bibl>L.  Abramowski, <title rend="italic">Untersuchungen zum Liber Heraclidis des
                Nestorius</title> (CSCO 242; 1963), 7–13.</bibl>
        <bibl>A.  Baumstark, ‘Griechische und hebräische Bibelzitate in der Pentateucherklärung
            Išôʿdâds von Merw’, <title rend="italic">OC</title> 11 (1911), 1–19.</bibl>
        <bibl>Becker, <title rend="italic">Fear of God</title>, 35–8, 113–4, 157–8.</bibl>
        <bibl>Labourt, <title rend="italic">Le christianisme dans l’empire perse</title>,
            163–91.</bibl>
        <bibl>W.  F.  Macomber, <title rend="italic">Six explanations of the liturgical feasts by
                Cyrus of Edessa. An East Syrian theologian of the mid sixth century</title> (CSCO
            356; 1974), VII–XII.</bibl>
        <bibl>P.  Peeters, ‘Observations sur la vie syriaque de Mar Aba, catholicos de l’Église
            perse (540–552)’, in <title rend="italic">Miscellanea G. Mercati</title>, vol. 5 (SeT
            125; 1946), 69–112.</bibl>
        <bibl>Vööbus, <title rend="italic">History of the School of Nisibis</title>, 161–70.</bibl>
        <bibl>W.  Wolska, <title rend="italic">La «Topographie chrétienne» de Cosmas Indicopleustès.
                Théologie et science au VIe siècle</title> (1962), 63–73.</bibl>
    </listBibl>
</listBibl>
```

**Comment by davidamichelson** [comment]
Okay, my mistake, I see that you did nest them. But it looks like we need to nest the sub-sub-sections still: see a search for (search for <label type="subsubsection">). These will need to be converted to tei:head and also get a nested listBibl.

**Comment by wsalesky** [comment]
Okay, nested subsections:
https://github.com/srophe/e-gedsh/tree/issue5

Should they have a type? Or is the TEI structure sufficient? (I lean toward the TEI structure being sufficient, but let me know if you disagree.)

**Comment by davidamichelson** [comment]
Happy to report that the nested listBibls up to three deep listBibl/listBibl/listBibl with tei:head are all now working well.

**Comment by wsalesky** [comment]
Actually the error on #7 is caused by the script that inserts the nested bibls. I think I see where the problem is. both use label/@type='subsection' so I need to add a filter for subsections followed by tei:bibl or tei:p.

**Comment by davidamichelson** [comment]
yes, that is correct, sorry for not making that clear.

**Comment by davidamichelson** [comment]
Except, the issue is that sometimes you might have:
tei:label
tei:p
tei:label
tei:p
tei:label
tei:bibl

in this case the last tei:label should go with the bibl not the p

**Comment by wsalesky** [comment]
Okay, updates for `div/@type='body'` and `listBibl`

https://github.com/srophe/e-gedsh/tree/issue5

**Comment by davidamichelson** [comment]
Yay! This is done and looks great! Please run it on the master branch version.

**Comment by wsalesky** [comment]
updated on master
