### ISSUE TITLE
Bibliography processing

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#54]
@wsalesky there seems to be a script running on bibl elements that looks for a period at the end of a bibliographic entry and adds one if there is not one in the TEI. Can you please turn this off? 

Take a look at the J. Isaac entry here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Abdisho-bar-Brikha&num=5. The entry ends with "(with AT)". There is no period in the print edition and we would like to maintain that practice here. Ute will instead check that all bibliographic entries have the correct punctuation. Thanks.

**Comment by davidamichelson** [comment]
@dlschwartz Because we want to harvest this data later for Syriaca, it would actually be good to use find and replace to find all these abbreviations and wrap them both with note and abbreviation so we can 1. expand them to "English Translation" etc. and 2. know that they are not not part of the citation but a note about a bibl. Would you be able to do that?

**Comment by davidamichelson** [comment]
I think using xpath find inside bibl combined with a regex about parens at the end of a line should work.

**Comment by dlschwartz** [comment]
@davidamichelson  all of the abbreviations in the body of the e-gedsh xml file are already wrapped in an abbr element. I did that with advanced find and replace before Ute went to work on the xml. Are you saying that you think I should go back to these, include an expan element with the full text, and then wrap all of that in a choice element? Would you prefer this just in the bibliographies or everywhere an abbreviation occurs?

I originally planned on doing this for all abbreviations but this is easier said than done. I suppose it's relatively simple if we only want to do this in bibliographies and we do not plan on visualizing the expan in e-gedsh. If we do, the expan visualization would get pretty unwieldy. See pp. xviii-xx of GEDSH. Let me know what you think.

**Comment by davidamichelson** [comment]
I think we might be speaking past each other here. Or something has gotten lost. These NT, LT, etc in the bibliography are not marked as abbr. Do we want them to be? I would just say in the bibliography so as to know they are not part of the citation.

**Comment by dlschwartz** [comment]
Sorry this post got past me. Something is wrong. I think you might be working with an old version of the xml. Every abbreviation is wrapped in an abbr element, except the abbreviations in the encoding of the abbreviation section of the doc. I guess we should look at this the next time we meet.

**Comment by dlschwartz** [comment]
@davidamichelson Do you want to weigh in on this again. I'd like to close this issue but I'm not sure if we ever addressed your concerns.
