### ISSUE TITLE
headwords should all be same font size

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#56]
Please adjust the display such that, as in the print version, the headword and the following words of the entry title are all in the same font size. The main headword should be in bold, the rest in normal font, but same font size.

**Comment by davidamichelson** [comment]
Ute, could youy clarify this a bit please? Do you mean the text that is in ab type="infobox"?

**Comment by wsalesky** [comment]
How is this: 
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Armalah-Ishaq&num=48

**Comment by upossekel** [comment]
Dear Winona,

 

Thanks for tending to these issues! This looks nice. But, examining the print copy more closely, the info next to headword is actually slightly smaller than the headword. Can you please adjust it accordingly? Just a little smaller than main headword would be excellent.

 

As you will have gathered, whenever I change the TEI, this is for some reason not reflected in the online version. David tells me the ‘hook’ is the problem. For a number of reasons, this would be important to get working properly very soon.

 

Many thanks!

Ute

**Comment by wsalesky** [comment]
@upossekel I am working on the webhooks issue today. Hope to have it up and working soon.

**Comment by wsalesky** [comment]
How about now for font size in the headwords?

**Comment by upossekel** [comment]
Beautiful! Love it.

 

Do you think you could also move the biblio’s left margin so as to be flush with the main text body? I.e., not indent it.

 

I also would be happy for us to omit the word ‘author’ under each entry. If the name appears, as it does in the encyclopedia, it should be clear enough that this is the author.

 

I hope you will get the ‘hook’ to work properly, so that I can see the changes that have been implemented. There are some issues that I’ve addressed with a find/replace all, that I would need to verify individually in the TEI unless it were easy to see on the website that they are fine.

 

Very many thanks indeed!

Ute

**Comment by wsalesky** [comment]
I'm happy to manually upload the new version of the data for you while I work on the webhooks bug. Just push the latest version to github and I will grab it and load it on the development server.

**Comment by davidamichelson** [comment]
I think you can just push the master branch as that has most of the recent changes. Thanks.

**Comment by wsalesky** [comment]
Done!

**Comment by upossekel** [comment]
We merged an updated version yesterday. 

 

Ute
