### ISSUE TITLE
supercript

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#57]
The superscript function for fonts does not seem to be working. See for example the biblio entry by Devos in the entry on Abgar the Hagiographer.

**Comment by davidamichelson** [comment]
Good catch. In the case like this it is helpful to include a line number from the code for Winona from the TEI if you can. This one is line 3096

@wsalesky it looks like one or more of the hi elements is not visualizing. @dlschwartz can give you a list of what they are: here is one example: ```<hi rend="superscript">e</hi> ```

**Comment by dlschwartz** [comment]
Sorry, I accidentally opened a new issue when I posted more info on this. Please see issue #65
