### ISSUE TITLE
hyperlinks for figures

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#59]
I'm sure you were planning this, but can the references to Figures get a hyperlink? E.g., Fig. 1 in entry on Abgarids.

**Comment by davidamichelson** [comment]
Yes these will be hyperlinked, perhaps we should add it now so you can check them

**Comment by wsalesky** [comment]
Where are the figures (for building the links), also, should we update the TEI to properly mark up the figures? They are just in a p element now.

**Comment by dlschwartz** [comment]
The whole English sentence is wrapped in a p element. But the figure is wrapped in a ref target with a URI: 
`<p>See <ref target="http://gedsh.bethmardutho.org/fig/2">Fig. 2</ref>.</p>`
Is there some other way we should do this?

@davidamichelson Am I right that we do not have any .jpg files yet? Let me know and I'll talk to George.

**Comment by wsalesky** [comment]
Ah, sorry, I had an old copy of the data on my machine. Let me take a look.

**Comment by wsalesky** [comment]
The links were already there, but they were styled to look like cross references, I changed them to be blue so they were more obviously links. They get an error page, I assume this is because the images are not yet up.
