### ISSUE TITLE
Web Hooks for e-gedsh

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#6]
@wsalesky Please point the webhooks here: https://github.com/srophe/e-gedsh/blob/master/egesdh-version-0-1.xml Thank you!

**Comment by wsalesky** [comment]
@davidamichelson I would like to change the structure of this repo, so that it can be deployed as an eXist app, if that is okay.

**Comment by davidamichelson** [comment]
yes please do.

**Comment by wsalesky** [comment]
Enabled. Will wait for some commits to the master branch to make sure they are working.
