### ISSUE TITLE
does i.e. get comma after it?

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#60]
In the print version of GEDSH there is no consistency in whether or not a comma is placed after i.e. About 1/3 or the cases seem to have a comma.

According to Chicago Style, section 6.43 (p. 321) there should be comma. Should I add it where it is lacking, marked with <corr>?

Personally, I find such inconsistencies slightly bothersome, so better to run a quick find and replace sooner rather than later.

Thanks!

**Comment by davidamichelson** [comment]
Related to https://github.com/srophe/e-gedsh/issues/61 We can discuss todau
