### ISSUE TITLE
web hooks

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#63]
@wsalesky could you please take a look at the web hooks again? We are working on the TEI and there seems to be a problem with the web hooks. After committing changes to the master branch they don't show up in the html. Is there a chance that the file is too big? Thanks!

**Comment by wsalesky** [comment]
I will take a look, I currently have no internet access but will check when I get home. (Webhook error messages can be checked on github, under settings, wehooks)

**Comment by dlschwartz** [comment]
Thanks @wsalesky. When I go there I see a red triangle with an exclamation mark. Whenever you get a chance to look at this is fine. Thanks.

**Comment by wsalesky** [comment]
Looks like we ran into a github file size limitation. There is another API we can use I will investigate it tomorrow. 

I loaded the latest data manually.

**Comment by wsalesky** [comment]
@dlschwartz @davidamichelson @upossekel I think I have fixed webhooks. Please let me know if it does not work the next time you commit. 
Thanks, 
-Winona
