### ISSUE TITLE
superscripts

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#65]
@wsalesky Many (but not all) of the superscripts in e-gedsh do not appear. See, for example, line 4597. In this bibl the two Roman numerals should both be followed by a superscripted "e": http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Aleppo. 
However, the superscripted "w" at line 21509 does appear: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Ethiopic-Christianity-Syriac-contacts-with

**Comment by wsalesky** [comment]
Should be fixed.
