### ISSUE TITLE
web display seems to have serious bugs

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#66]
I see the web display is updated today. But now some new  bugs seem to have appeared. For example, in entry on Aba I, first item in bibliography: words are missing in the parentheses (repr.). Chabot: words missing in parenthesis. Scher: series title missing.

Could you please fix this very soon? I won't be able to continue with proofing entries before this is remedied.

Many thanks!
Ute

**Comment by wsalesky** [comment]
@upossekel do you mean in the Sources section? Or in the body of the text? I do see the missing words in parenthesis in the source, just let me know if you see it anywhere else. Thanks.

**Comment by upossekel** [comment]
This seems to be a problem only in bibliography.
Since I posted a lot of issues, it it is easier, we might be able to talk by phone or Skype tomorrow.

Very many thanks!
Ute

**Comment by wsalesky** [comment]
Let me see what I can fix tonight, if there are still outstanding issues I am available in the afternoon (1ish EST).

**Comment by wsalesky** [comment]
@upossekel  This one should be fixed. If it is you may close the issue.

**Comment by wsalesky** [comment]
@davidamichelson @dlschwartz I have coded around the github file size issue, and am now facing a seriouse eXist limitation. Today I will be installing a newer version of eXist to see if it offers a fix. Will keep you updated, but it is unlikely this will be fixed this week. If the new version does fix the issue, we will have to update the version of dev. Sorry for the delay.

**Comment by dlschwartz** [comment]
Thanks @wsalesky!

**Comment by wsalesky** [comment]
I think this one has been resolved as well.
