### ISSUE TITLE
corrections don't display

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#68]
I made a number of corrections to the TEI but these don't display. Example: entry Abdisho of Gazarta. Bibliography. Lampert is actually not J. but A. Line 2874. 
Similar: title of Lampart's book needs colon before 'Joseph'. Line 2874 also.

**Comment by wsalesky** [comment]
This is a display issue not a coding issue. I think. 
@dlschwartz we may need to discuss how to display sic/corr elements.

**Comment by dlschwartz** [comment]
@wsalesky Does my comment on issue #73 address this sufficiently?
@upossekel Do please wrap the sic and corr elements in a choice element.

**Comment by upossekel** [comment]
Hm, you mean with putting corrections in <choice>? I think maybe not quite.

 

Example: entry on Abgarids

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Abgarids-of-Edessa 

 

middle of second paragraph, the word ‘colonia’ should be corrected to appear in italics. Now both are side by side, old and new version, with old version in parentheses.

 

Line 3139 of code.

 

Ute

**Comment by wsalesky** [comment]
@dlschwartz yes, that makes sense. I will add it to the xslt, by end of day.

**Comment by wsalesky** [comment]
Resolved
