### ISSUE TITLE
Adding Structure to the Schema

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#7]
@dlschwartz @wsalesky 

Beyond the few initial transformations, I am wondering if we need to add more structure in general to the entries. D could you discuss with W and decide?

At present here is the two structures:

For full entries:

- tei:div @type="entry"
  - tei:head
  - tei:ab @type="infobox" (optional, not always present, never multiple)
  - tei:p (multiple)
  - tei:listBibl
     - tei:label (optional, multiple)
     - tei:bibl (multiple)
  - tei:byline

Should we add a  tei:div @type="body" like this?

- tei:div @type="entry"
  - tei:head
  - tei:ab @type="infobox" (optional, not always present, never multiple)
  - tei:div @type="body"
     - tei:p (multiple)
  - tei:listBibl
     - tei:label (optional, multiple)
     - tei:bibl (multiple)
  - tei:byline

For cross-ref entries:

- tei:div @type="entry"
  - tei:head
  - tei:ab @type="crossreference"

Do we need to wrap the tei:ab in a div? I prefer not to.

Please comment.

**Comment by wsalesky** [comment]
I'm not sure we need the extra structure. The only one I would add would be the `div/@type="body"`

**Comment by davidamichelson** [comment]
Okay, please write a script that wraps all div[@type="entry"]/tei:p in a tei:div[@type="body"]

**Comment by wsalesky** [comment]
Done. See this branch : https://github.com/srophe/e-gedsh/tree/issue5
If it looks good we can merge it into the master.

**Comment by davidamichelson** [comment]
Alas, this almost worked. There were, however, some tei:labels between tei:p that then got pushed out and excluded from the div in the transformation. 

There are not many, this applies to 13 entries, shall we just re-insert them by hand?

**Comment by davidamichelson** [comment]
example:

```
<div type="entry">
                <head>Peshitta</head>
                <label type="subsection">The Name ‘Peshitta’</label>
                <label type="subsection">Origin and Dating of the OT Peshitta</label>
                <label type="subsection">Origin and Dating of the NT Peshitta</label>
                <label type="subsection">Nature of the OT Translation</label>
                <label type="subsection">Nature of the NT Translation</label>
                <label type="subsection">The Importance of the Peshitta</label>
                <label type="subsection">Text Editions</label>
                <label type="subsection">Translation into English</label>
                <div type="body">
                    <p>The name ‘Peshitta’ is
```

**Comment by wsalesky** [comment]
Well, I can rewrite it to include them. I don't think it would be that difficult. Let me know which you want. I have to rerun the other script anyway to nest the sub-sub-sections.

**Comment by davidamichelson** [comment]
Okay please do.

**Comment by wsalesky** [comment]
This should not include the tei:ab elements correct?

**Comment by davidamichelson** [comment]
Right not the tei:ab just the tei:labels that precede tei:p

Not all entries have a tei:ab

-D

**Comment by wsalesky** [comment]
Okay, updated version with labels wrapped in body here:
https://github.com/srophe/e-gedsh/tree/issue5

**Comment by davidamichelson** [comment]
Sorry @wsalesky but it only partially worked. For some reason at line 5989 of the original file, the label: <label type="subsection">Syriac Translations of the Old Testament</label> was turned into a listBibl and Head instead of p and label in https://github.com/srophe/e-gedsh/tree/issue5

**Comment by wsalesky** [comment]
Interesting. :(

**Comment by davidamichelson** [comment]
So when you resolve this, please run the script for #7 as well. #7 appears to be working fine.

**Comment by wsalesky** [comment]
updated on master
