### ISSUE TITLE
curved or smart quotes

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#71]
When I insert a single quote sign in TEI, this does not appear as smart quote.
Example: line 3093, before 'Abgar'. This initially was the wrong sign, but not it only appears as straight quote, not curved.

**Comment by dlschwartz** [comment]
Ute, can you clarify? It is only in the TEI that they don't show up as smart quotes or is it also in the HTML?

**Comment by upossekel** [comment]
It is in both.

**Comment by dlschwartz** [comment]
@upossekel This is a font issue. Let me look into and get back to you.

**Comment by dlschwartz** [comment]
Do you still have this problem @upossekel? I see smart quotes throughout the HTML which is what really matters. Please close this issue if you think it has been resolved. Thank you.

**Comment by upossekel** [comment]
It has not been resolved. If smart quotes need to be added, I cut and paste from a Word document or from the XML file.

**Comment by dlschwartz** [comment]
@upossekel, I didn't know that, I'm sorry. I thought we had discussed this actually. You have to type your quotes in the author mode with the right settings chosen in oxygen. Go to Options, Preferences, Editor, Edit modes, Author, AutoCorrect, and then select Smart Quotes at the bottom. Switching to author mode isn't ideal but it is likely easier than cut and paste.  I hope that helps.
