### ISSUE TITLE
correction function

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#73]
Whenever I made a correction the other day, this does not display properly. Not sure I coded wrong or if it is a bug.

Example: line 3277, where I think the word 'Admonition' ought to be capitalized as it is a title and as it appears such below in same entry. On website, this appears as (a).

Please help me sort this out. Can't really proceed otherwise.

Thanks!

**Comment by wsalesky** [comment]
Please include links to problem entries, will make troubleshooting go
faster.

**Comment by dlschwartz** [comment]
@upossekel I would recommend encoding this in the following way.
`<choice><sic>admonition</sic><corr>Admonition</corr></choice>`

@wsalesky Ute will be fixing typos, etc. by using choice, sic, and corr elements or choice, reg, orig elements. We want an accurate transcription but with corrections. Also, we want to be able to show the editors of the print version all the changes we've made. Can you ensure that this visualization displays the corr and reg but not the sic and orig? Thanks!

**Comment by wsalesky** [comment]
@dlschwartz do you want any indication that this is a correction in the html?

**Comment by upossekel** [comment]
I think not. Just in the TEI so we can run changes by the editors of the print version. But I will let Dan comment also.

 

Ute

**Comment by dlschwartz** [comment]
@wsalesky We simply want this in the TEI, at least for right now. We will run these changes past the editors of the print version so that they can sign off on any changes to the text. We will also be able to give them a list of errors in case they want to produce another edition of the print volume.

**Comment by wsalesky** [comment]
Okay. Thanks.
