### ISSUE TITLE
not sure where to put spaces

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#76]
entry on Adullah II Sattuf
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Abgar-the-Hagiographer&num=10

Middle of second paragraph. the spacing before the words 'Ignatius Ephrem Rahmani' (which has a cross reference) is not right, also just below with Syr. Orth. Patr. Abdulmasih. Where in TEI do the spaces go? between angle brackets?

Thanks.

**Comment by wsalesky** [comment]
Your spaces look fine. I think that is an xslt issue which I will fix.

**Comment by upossekel** [comment]
Many thanks!

Ute

**Comment by wsalesky** [comment]
Fixed, see:
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Abdullah-II-Sattuf
