### ISSUE TITLE
corrections to bibliography don't show properly online

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#79]
Good morning, Winona.

Thanks for all your work on fixing various issues yesterday! It seems that my correction to the text of entries now appear correctly online, but not those in the bibliography.

Example: Abraham bar Dashandad.
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?fq=;fq-Browse:A&id=http://gedsh.bethmardutho.org/Abraham-bar-Dashandad

Here the correction in text (code line 3274) displays fine. But the corrections in the bibliography section (code lines 3314 amd 3316) do not.

Thanks for your help!
Ute

**Comment by wsalesky** [comment]
That should fix it. However, I noticed there is a spacing error. Please make sure you add a space before the t:choice element, if it is within the element the stylesheet ignores it. 
Thanks!

**Comment by upossekel** [comment]
Thanks, Winona! Much appreciated.

 

Best,

Ute
