### ISSUE TITLE
online version has issues with spaces

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#82]
There are still problems, it seems, with placement of spaces.

Examples:
1. 
Entry on Abdullah I bar Stephanos, near and of body text. Online there is an additional space after NT. Code line 2909.

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Abdullah-I-bar-Stephanos&num=7

2. 
Same entry, in bibliography, Brock entry, there is no space before K. Cathcart (line 2917).
After the word 'cent.' the online version puts an additional space before the parentheses.

3.
Entry on Ahiqar, second paragraph, near end.
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Ahiqar&num=22

XML line 3966.

This may have to do with the <abbr>.

**Comment by wsalesky** [comment]
Fixed. It was indeed the t:abbr element.
