### ISSUE TITLE
still problems with spaces and <abbr> element

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#84]
There seems to be still a bug concerning this. In entry headlines, the abbreviated words in square brackets seem to cause insertion of an extra space on website, but only in some cases.

space after  'Chald.'
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Abdisho-of-Gazarta&num=6

space before and after 'Syr. Orth.
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Abdullah-I-bar-Stephanos&num=7

**Comment by wsalesky** [comment]
This one is a bug in the xslt. I have fixed it.
