### ISSUE TITLE
placement of spaces - new issue

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#85]
Yesterday I ran a find/replace all such as to place a comma after all those instances of e.g. that are not followed by a comma. (There was no uniformity in text.) It appears that now on the website those commas are not followed by a space before the next word. This may either be a problem with my coding of the XML (though I had placed a space in after the <choice> element closes, or one of the space-placement related bugs. Please advise. 

Example:
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Abraham-of-Nathpar&num=16

Code line 6562.

**Comment by wsalesky** [comment]
These spaces would show up if the spaces were within th `<corr>` tags. 
Example: `<corr>e.g., </corr>`

**Comment by wsalesky** [comment]
This seems to be resolved?

**Comment by dlschwartz** [comment]
Yes, I believe it is. Thanks.
