### ISSUE TITLE
hyperlink

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#86]
The Alqosh entry has link to a website at end of bibliography. How do we create a hyperlink?

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Alqosh&num=30

Line 4791

**Comment by wsalesky** [comment]
I would use a t:ref or t:ptr element. Deferring to @dlschwartz for final decision.

**Comment by dlschwartz** [comment]
@upossekel Please wrap this and other similar web addresses in <ref target="www.xxx.org">. Thanks.

**Comment by dlschwartz** [comment]
Sorry, that should have read:
@upossekel Please wrap this and other similar web addresses in <ref target="www.xxx.org">. Thanks.

**Comment by dlschwartz** [comment]
@upossekel Sorry, I keep messing this up. It should read `<ref target="www.alqosh.net">` Did that come through? It's a ref element and a target attribute that includes the web address.
