### ISSUE TITLE
superscripts should not be italicized

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#87]
In bibliographies of various entries, there is reference to second edition of Enclyclopedia Islam., cited as EI superscript '2'. The 2 should not be in italics. I changed this in one instance - code line 1519-1520. But now it appears as if the superscript 2 is followed by an empty space before the comma. 

I'd like to be sure this is all right before running find/replace all.

Entry on Amid, biblio item by Canard (fourth in list).
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Amid

**Comment by wsalesky** [comment]
Looks like it is just a formatting issue. I suspect the css. You can go
ahead and make the change. I will change the display, but will not get to
it today.
-Winona
