### ISSUE TITLE
should obvious spelling errors be marked with 'choice' as well?

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#88]
Should simple spelling mistakes, such as 'bacame' for 'became' or Res grestae for Res gestae be marked by 'choice' element as well? To me there does not seem anything to choose but to tacitly correct these. I will add sic/corr, however. Let me know if you wish this to be marked with choice also.

**Comment by dlschwartz** [comment]
@upossekel Yes, this allows two important things. One, it gives an accurate rendering of the print edition in digital form. Also, it allows us to easily hand George a list of all mistakes in the print edition. He wants this in case there is a second edition of GEDSH. Thanks
