### ISSUE TITLE
subsection heading should visually be enhanced

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#94]
In entry on Art and architecture, the subsection headings should visually be enhanced. Perhaps slightly larger font, and more space between heading and text.

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Art-and-architecture&num=50

Line 7276 and elsewhere with element 'subsection'.

**Comment by wsalesky** [comment]
Fixed
