### ISSUE TITLE
problem with 'web hook'

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#95]
The changes I made and committed, and synced, today are not displaying. Is the web hook not working at the moment? It was fine just a day or two ago.

**Comment by wsalesky** [comment]
The webhook is complaining about a malformed t:hi element. 
Here is the error:

> Element type "hi" must be followed by either attribute specifications, "&gt;" or "/&gt;"

I don't see it on a quick look, and I was able to load the file manually. Let me know if it continues to be a problem.

**Comment by davidamichelson** [comment]
Ute, did you try checking the validation (red/green) in Oxygen on the file?
