### ISSUE TITLE
font size 

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#96]
the font size for the text line 12158, formatted as 'head', should not be larger than the text in entry on Bible, General.

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Bible-General&num=104

**Comment by wsalesky** [comment]
@upossekel Not sure I understand this one? Could you clarify?

**Comment by wsalesky** [comment]
I think this can be closed.
