### ISSUE TITLE
font size for 'subsection'

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#97]
The 'subsection' headings in certain entries might well be formatted so as to stand out a little more. I suggest at least a bit more space between subsection text and next paragraph. Or maybe slightly larger font?

Example, entry on Bible, General (but there are others as well).
Line 11968 and elsewhere.

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Bible-General&num=104

**Comment by wsalesky** [comment]
I think this has been resolved.

**Comment by dlschwartz** [comment]
I agree. Sorry, this one got past me over the holidays.
