### ISSUE TITLE
extra space appears

### ISSUE THREAD

**Issue by upossekel** [srophe/e-gedsh#98]
In the entry 'Bible, NT mss.' there is an extra space in the expression 'Sinaitic Ms.' [single quotes are part of text]. Line 12,316. This is in paragraph numbered 2, middle.

http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Bible-New-Testament-manuscripts&num=106

**Comment by wsalesky** [comment]
Resolved.
